- .github/workflows/ci.yaml
- .gitignore
- codecov.yml
> chore: add codecov for testing

- CONTRIBUTING.md
- README.md
> chroe: add README.md

- README.md
> docs: optimize Community description in README.md

- src/config/dfdaemon.rs
> feat: rename default task dir

- src/config/dfdaemon.rs
- Add content dir and metadata dir.
> feat: add content dir and metadata dir

- Cargo.toml
- src/bin/dfget/main.rs
- src/config/dfdaemon.rs
- src/config/dfget.rs
- src/lib.rs
- src/logging/mod.rs
> feat: add dfget command args

- src/bin/dfget/main.rs
- src/config/dfget.rs
> feat: add log_dir to dfget args

- Cargo.toml
- src/bin/dfget/main.rs
> feat: add args in dfget command

- src/bin/dfdaemon/main.rs
- src/bin/dfget/main.rs
- src/bin/dfstore/main.rs
- src/config/dfstore.rs
- Add args to dfdaemon and dfstore.
> feat: add args to dfdaemon and dfstore

- src/bin/dfstore/main.rs
> feat: add subcommand to dfstore

- Cargo.toml
- src/bin/dfget/main.rs
- src/logging/mod.rs
> feat: add logging to client

- src/bin/dfget/main.rs
- Set default value to dfget args.
> feat: set default value to dfget args

- .github/PULL_REQUEST_TEMPLATE.md
- src/logging/mod.rs
- Add directive to env_filter by arg level.
> feat: add directive to env_filter by arg level

- src/bin/dfdaemon/main.rs
- src/bin/dfget/main.rs
- src/bin/dfstore/main.rs
- src/logging/mod.rs
> feat: init logging without ansi

- src/bin/dfdaemon/main.rs
- src/bin/dfget/main.rs
- src/bin/dfstore/main.rs
- src/config/dfdaemon.rs
- src/config/dfget.rs
- src/config/dfstore.rs
> feat: add NAME to different package

- src/config/dfdaemon.rs
- src/config/dfget.rs
- src/config/dfstore.rs
- src/logging/mod.rs
> feat: remove ansi in stdout logging

- src/config/dfdaemon.rs
> feat: serde parses config with lower camel case

- Cargo.toml
- src/bin/dfdaemon/main.rs
- src/config/dfdaemon.rs
> feat: add error enum for config

- src/config/dfdaemon.rs
- src/tracing/mod.rs
- Add Metrics and Tracing to Config.
> feat: add Metrics and Tracing to Config

- Cargo.toml
- src/bin/dfdaemon/main.rs
- src/bin/dfget/main.rs
- src/bin/dfstore/main.rs
- src/tracing/mod.rs
- Add jaeger layer to subscriber.
> feat: add jaeger layer to subscriber

- Cargo.toml
- src/config/dfdaemon.rs
> feat: add fields to config

- Cargo.toml
- src/bin/dfdaemon/main.rs
- src/config/dfdaemon.rs
- Support to get local ip with local-ip-address.
> feat: support to get local ip with local-ip-address

- src/bin/dfdaemon/main.rs
- src/config/dfdaemon.rs
- Change convert to private func in config.
> feat: change convert to private func in config

- src/bin/dfdaemon/main.rs
- src/config/dfdaemon.rs
- src/health/mod.rs
- src/lib.rs
- src/metrics/mod.rs
> feat: add health server

- src/config/dfdaemon.rs
> feat: remove health config

- src/bin/dfdaemon/main.rs
- src/health/mod.rs
- src/metrics/mod.rs
- Add graceful shutdown to tokio.
> feat: add graceful shutdown to tokio

- src/bin/dfdaemon/main.rs
- src/health/mod.rs
- src/lib.rs
- src/metrics/mod.rs
- src/shutdown.rs
- Add graceful shutdown to multi servers.
> feat: add graceful shutdown to multi servers

- .github/workflows/lint.yml
- Cargo.toml
- src/bin/dfdaemon/main.rs
- src/config/dfdaemon.rs
- src/health/mod.rs
- src/metrics/mod.rs
- src/shutdown.rs
- src/storage/content.rs
- src/storage/metadata.rs
- Add metadata feature with rocksdb.
> feat: add metadata feature with rocksdb

- src/bin/dfdaemon/main.rs
- src/config/dfdaemon.rs
- src/metrics/mod.rs
- src/storage/content.rs
- src/storage/metadata.rs
- src/storage/mod.rs
- Add storage and content to dfdaemon.
> feat: add storage and content to dfdaemon

- src/storage/metadata.rs
- src/storage/mod.rs
> feat: add error to storage

- src/metrics/mod.rs
- src/storage/metadata.rs
- src/storage/mod.rs
> feat: optimize get_piece_state in storage

- src/metrics/mod.rs
- src/storage/metadata.rs
- src/storage/mod.rs
> feat: add reuse_piece to storage

- src/storage/metadata.rs
- src/storage/mod.rs
> feat: remove state for piece

- Cargo.toml
- src/backend/http.rs
- src/storage/content.rs
- src/storage/mod.rs
> feat: add tokio to http backend and storage

- Cargo.toml
- src/bin/dfdaemon/main.rs
- src/bin/dfget/main.rs
- src/bin/dfstore/main.rs
> chore: rename crate name to dragonfly-client

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- Cargo.toml
- src/config/mod.rs
- src/grpc/health.rs
- src/grpc/manager.rs
- src/grpc/mod.rs
- src/grpc/scheduler.rs
- src/grpc/security.rs
> feat: add grpc client implements

- src/grpc/dfdaemon.rs
- src/grpc/health.rs
- src/grpc/mod.rs
- src/grpc/scheduler.rs
> feat: add client of dfdaemon grpc

- Cargo.toml
- src/bin/dfdaemon/main.rs
- src/config/dfdaemon.rs
- src/config/mod.rs
- src/grpc/dfdaemon.rs
- src/health/mod.rs
- src/metrics/mod.rs
- src/tracing/mod.rs
> feat: add CompressionEncoding to dfdaemon grpc client

- Cargo.toml
- src/bin/dfdaemon/main.rs
- src/grpc/dfdaemon.rs
- src/grpc/health.rs
- src/grpc/manager.rs
- src/grpc/scheduler.rs
- src/grpc/security.rs
- src/health/mod.rs
> feat: add dfdaemon grpc server

- Cargo.toml
- src/grpc/dfdaemon.rs
> feat: add reflection to dfdaemon grpc server

- Cargo.toml
- src/announcer/mod.rs
- src/backend/http.rs
- src/bin/dfdaemon/main.rs
- src/config/dfdaemon.rs
- src/config/mod.rs
- src/grpc/dfdaemon.rs
- src/grpc/health.rs
- src/grpc/manager.rs
- src/grpc/mod.rs
- src/grpc/scheduler.rs
- src/grpc/security.rs
- src/lib.rs
- src/storage/content.rs
- src/storage/metadata.rs
- src/storage/mod.rs
- src/utils/id_generator.rs
- src/utils/mod.rs
> feat: add announcer and id_generator to dfdaemon

- src/bin/dfdaemon/main.rs
- src/config/dfdaemon.rs
- src/grpc/dfdaemon.rs
- src/grpc/health.rs
- src/grpc/manager.rs
- src/grpc/scheduler.rs
- src/grpc/security.rs
- src/tracing/mod.rs
> feat: use channel to connect grpc

- Cargo.toml
- src/announcer/mod.rs
- src/grpc/dfdaemon.rs
- src/grpc/manager.rs
- src/grpc/scheduler.rs
> feat: update dragonfly-api verison and tonic version

- Cargo.toml
- src/announcer/mod.rs
- src/grpc/manager.rs
> feat: delete seed peer when shutting down

- Cargo.toml
- src/announcer/mod.rs
> feat: add object_storage_port and scheduler_cluster_id to SchedulerAnnouncer

- src/announcer/mod.rs
- src/bin/dfdaemon/main.rs
- src/dynconfig/mod.rs
> feat: manager_client use arc to avoid tokio:span move variable

- src/announcer/mod.rs
- src/bin/dfdaemon/main.rs
- src/dynconfig/mod.rs
- src/grpc/dfdaemon.rs
- src/grpc/health.rs
- src/grpc/scheduler.rs
- src/grpc/security.rs
> feat: replace mut with clone in grpc

- src/announcer/mod.rs
- src/bin/dfdaemon/main.rs
- src/dynconfig/mod.rs
- src/grpc/scheduler.rs
> feat: add RwLock to dynconfig data

- src/bin/dfdaemon/main.rs
- src/shutdown.rs
> feat: optimize shutdown and add clone to shutdown

- src/announcer/mod.rs
- src/bin/dfdaemon/main.rs
- src/dynconfig/mod.rs
- src/grpc/dfdaemon.rs
- src/health/mod.rs
- src/metrics/mod.rs
> feat: run server uses clone shutdown

- src/dynconfig/mod.rs
- src/grpc/health.rs
1. use channel from_share instead of from_static
2. reduce write lock scope when refrash config from remote
> refactor: reduce the lock scope

- src/dynconfig/mod.rs
> fix: get available schedulers from manager

- src/storage/metadata.rs
- src/storage/mod.rs
> feat: optimize storage func

- src/grpc/dfdaemon.rs
- src/grpc/scheduler.rs
- src/lib.rs
- src/storage/content.rs
- src/storage/mod.rs
- src/task/mod.rs
> feat: implement download piece in task

- src/backend/http.rs
- src/bin/dfdaemon/main.rs
- src/lib.rs
- src/task/mod.rs
> feat: add download_piece_from_source to task

- src/utils/digest.rs
- src/utils/mod.rs
> feat: add digest to utils

- Cargo.toml
- src/lib.rs
- src/storage/content.rs
- src/storage/mod.rs
- src/task/mod.rs
> feat: calculate digest and compare digest when write piece finished

- Cargo.toml
- src/bin/dfdaemon/main.rs
- src/grpc/dfdaemon.rs
- src/grpc/scheduler.rs
- src/storage/metadata.rs
- src/storage/mod.rs
- src/task/mod.rs
> feat: add stat task to dfdaemon

- src/grpc/dfdaemon.rs
- src/storage/metadata.rs
> feat: add prefix extractor to rocksdb

- src/storage/metadata.rs
- src/storage/mod.rs
> feat: add get_pieces with prefix_iterator

- Cargo.toml
- src/grpc/dfdaemon.rs
- src/task/mod.rs
> feat: implement GetPieceNumbers grpc api

- src/grpc/dfdaemon.rs
- src/storage/mod.rs
- src/task/mod.rs
- src/task/piece.rs
> feat: add piece manager

- Cargo.toml
- src/bin/dfdaemon/main.rs
- src/grpc/dfdaemon.rs
- src/lib.rs
- src/storage/metadata.rs
- src/storage/mod.rs
- src/task/mod.rs
- src/task/piece.rs
- src/utils/digest.rs
- src/utils/id_generator.rs
> feat: add download_into_file to task

- src/storage/metadata.rs
- src/storage/mod.rs
- src/task/mod.rs
- src/task/piece.rs
- Add `calculate_numbers_by_range` to task.
- Add `get_by_numbers` to task.
- Handle download with range parameter.
> feat: handle download with range parameter

- Cargo.toml
- src/grpc/dfdaemon.rs
> feat: change download task response to stream

- Cargo.toml
- src/grpc/dfdaemon.rs
- src/task/mod.rs
- src/task/piece.rs
> feat: implemented download task with download progress channel

- src/grpc/dfdaemon.rs
> feat: implement download task in client

- Cargo.toml
- src/bin/dfget/main.rs
- src/grpc/dfdaemon.rs
> feat: support unix socket for dfdaemon download client

- Cargo.toml
- src/bin/dfget/main.rs
- src/grpc/dfdaemon.rs
- src/storage/metadata.rs
- src/task/mod.rs
> feat: parse dfget's command arguments

- src/bin/dfdaemon/main.rs
- src/grpc/dfdaemon.rs
> feat: optimize dfdaemon grpc server with graceful shutdown

- src/grpc/dfdaemon.rs
- src/grpc/manager.rs
- src/grpc/scheduler.rs
- src/grpc/security.rs
- src/storage/content.rs
- src/storage/metadata.rs
- src/storage/mod.rs
- src/task/mod.rs
- src/task/piece.rs
> feat: add instrument macro to func

- src/grpc/dfdaemon.rs
- src/storage/content.rs
- src/storage/metadata.rs
- src/storage/mod.rs
- src/task/mod.rs
- src/task/piece.rs
> feat: download_task with spawn

- src/grpc/dfdaemon.rs
- src/storage/metadata.rs
- src/storage/mod.rs
- src/task/mod.rs
- src/task/piece.rs
> feat: add span for tokio::spawn and optimize download from source

- src/task/mod.rs
> feat: report peer download status to scheduler

- src/storage/content.rs
- src/storage/metadata.rs
- src/storage/mod.rs
- src/task/mod.rs
- src/task/piece.rs
- src/tracing/mod.rs
> feat: optimize log format and refactor spans

- src/grpc/dfdaemon.rs
- src/grpc/health.rs
- src/grpc/manager.rs
- src/grpc/scheduler.rs
- src/grpc/security.rs
> feat: add make_request to grpc client

- src/backend/http.rs
- src/backend/mod.rs
- src/bin/dfdaemon/main.rs
- src/bin/dfget/main.rs
- src/bin/dfstore/main.rs
- src/config/dfdaemon.rs
- src/grpc/dfdaemon.rs
- src/task/mod.rs
- src/task/piece.rs
> feat: add piece_timeout for downloading from origin

- src/config/dfdaemon.rs
- src/grpc/dfdaemon.rs
- src/lib.rs
- src/task/mod.rs
- src/task/piece.rs
> feat: concurrent downoad pieces from source with tokio

- Cargo.toml
- src/config/dfdaemon.rs
- src/grpc/dfdaemon.rs
- src/grpc/mod.rs
- src/lib.rs
- src/storage/metadata.rs
- src/storage/mod.rs
- src/task/mod.rs
- src/task/piece.rs
> feat: concurrent download from source with scheduler

- src/task/piece.rs
> feat: concurrent collect piece metadatas from remote peers

- src/task/mod.rs
> feat: wait for the latest message to be sent

- src/config/dfdaemon.rs
- src/lib.rs
- src/task/mod.rs
> feat: add max_schedule_count for downloading task

- Cargo.toml
- src/grpc/dfdaemon.rs
- src/task/piece.rs
> feat: add download piece to piece manager

- src/bin/dfdaemon/main.rs
- src/lib.rs
- src/storage/mod.rs
- src/task/piece.rs
> feat: wait for downloading piece finished

- Cargo.toml
- src/config/dfdaemon.rs
- src/grpc/dfdaemon.rs
- src/lib.rs
- src/storage/mod.rs
- src/task/mod.rs
- src/task/piece_collector.rs
> feat: use piece collector for downloading pieces

- src/gc/mod.rs
- src/storage/content.rs
- src/storage/metadata.rs
- src/storage/mod.rs
> feat: evict task cache by ttl

- src/grpc/scheduler.rs
> feat: if scheduler client connect failed, refresh scheduler addresses

- src/announcer/mod.rs
- src/bin/dfget/main.rs
- src/config/dfdaemon.rs
> feat: change all of the ports in service

- Cargo.toml
- src/grpc/dfdaemon_upload.rs
> feat: add download_task to DfdaemonUpload for seed peer

- src/bin/dfdaemon/main.rs
- src/utils/id_generator.rs
> feat: add seed peer tag to IDGenerator

- src/grpc/dfdaemon_download.rs
- src/grpc/dfdaemon_upload.rs
- src/grpc/health.rs
> feat: add host_id to span and add instrument to health grpc

- src/bin/dfdaemon/main.rs
- src/bin/dfget/main.rs
- src/config/dfdaemon.rs
- src/grpc/health.rs
- src/grpc/manager.rs
- src/lib.rs
> feat: check manager addrs healthy and add validation to config

- src/bin/dfdaemon/main.rs
- src/config/dfdaemon.rs
- src/metrics/mod.rs
> refactor: serde parse config with default macros

- src/bin/dfdaemon/main.rs
- src/bin/dfget/main.rs
- src/grpc/dfdaemon_download.rs
- src/grpc/dfdaemon_upload.rs
- src/grpc/health.rs
> feat: download and upload support health check

- src/utils/id_generator.rs
> fix: idgen generate peer id by seed peer

- Cargo.toml
- src/task/mod.rs
> feat: add send log for scheduling parent

- src/grpc/dfdaemon_download.rs
- src/grpc/dfdaemon_upload.rs
- src/task/mod.rs
- src/task/piece_collector.rs
> fix: DashMap deadlock in collector

- src/grpc/dfdaemon_upload.rs
- src/storage/content.rs
- src/storage/metadata.rs
- src/task/piece_collector.rs
- src/tracing/mod.rs
> feat: if collected piece finished, abort all task

- src/gc/mod.rs
- src/storage/metadata.rs
- src/storage/mod.rs
> fix: calculate need evict space and optimize uploading_count in task

- .github/workflows/docker.yml
- Dockerfile
> feat: add dfdameon Dockerfile and push docker actions

- Dockerfile
> chore: remove Cargo.lock in Dockerfile

- Dockerfile
> chore: add pkgconfig and openssl-dev to Dockerfile

- Dockerfile
> chore: add protoc to Dockerfile

- Dockerfile
> chore: add protobuf-dev to Dockerfile

- Dockerfile
> chore: add clang-dev to Dockerfile

- Dockerfile
> chore: add llvm-dev to Dockerfile

- Dockerfile
> chore: add clang to Dockerfile

- Dockerfile
> chore: change build image to rust in Dockerfile

- src/task/piece.rs
> feat: remove content length is zero log and range length is zero log

- .github/workflows/docker.yml
- .github/workflows/release.yml
> chore: add release actions

- Cargo.toml
> chore: update cargo version

- .github/workflows/docker.yml
> chore: change image name in ghcr.io

- .github/workflows/release.yml
> chore: add publish-crates step in release

- .github/workflows/release.yml
> chore: enable draft feature for release

- Cargo.toml
- src/announcer/mod.rs
- src/config/dfdaemon.rs
- src/dynconfig/mod.rs
- src/grpc/manager.rs
> feat: remove health config and object storage config

- Cargo.toml
- src/bin/dfdaemon/main.rs
- src/bin/dfget/main.rs
- src/bin/dfstore/main.rs
- src/tracing/mod.rs
> feat: support to specify max files of tracing

- Cargo.toml
- src/bin/dfdaemon/main.rs
- src/config/dfdaemon.rs
- src/config/mod.rs
- src/gc/mod.rs
- src/storage/content.rs
- src/storage/metadata.rs
- src/storage/mod.rs
> feat: change data_dir to storage's dir

- src/bin/dfdaemon/main.rs
- src/config/dfdaemon.rs
- src/config/mod.rs
- src/task/mod.rs
> feat: optimize config in dfdaemon

- Cargo.toml
> chore: update cargo version to v0.1.4

- .github/workflows/docker.yml
> chore: add cache docker layers step to docker.yaml

- Cargo.toml
- Dockerfile
- src/bin/dfdaemon/main.rs
> feat: change BASE_IMAGE in Dockerfile and remove useless logs

- Cargo.toml
- Dockerfile
> chore: change base image to debian:bookworm-slim in runtime image

- Cargo.toml
- src/config/dfdaemon.rs
> feat: support to parse duration by humantime-serde

- Cargo.toml
- src/grpc/dfdaemon_download.rs
> feat: create socket path for dfdaemon download

- Cargo.toml
- Dockerfile
> chore: add wget to client image

- Dockerfile
- src/bin/dfdaemon/main.rs
- src/bin/dfget/main.rs
- src/bin/dfstore/main.rs
- src/tracing/mod.rs
> feat: add verbose options to command

- Cargo.lock
- Cargo.toml
- src/grpc/scheduler.rs
> feat: refresh addresses of available schedulers when call grpc api

- src/config/dfdaemon.rs
- src/grpc/scheduler.rs
- src/task/mod.rs
> feat: get hashring by prefix string in task id

- src/grpc/scheduler.rs
- src/task/mod.rs
- src/task/piece_collector.rs
> feat: add log for collecter spawn

- src/grpc/scheduler.rs
> fix: update available scheduler and addresses

- Cargo.lock
- Cargo.toml
- src/task/mod.rs
> feat: report candidate parents when download failed

- src/announcer/mod.rs
- src/grpc/scheduler.rs
> feat: sync available scheduler addresses from manager

- src/dynconfig/mod.rs
- src/grpc/dfdaemon_download.rs
- src/grpc/dfdaemon_upload.rs
- src/grpc/health.rs
- src/grpc/manager.rs
- src/grpc/scheduler.rs
- src/task/piece.rs
> feat: add connect error log to grpc client

- Cargo.toml
> chore: update cargo version to v0.1.12

- Cargo.lock
- Cargo.toml
- src/config/dfdaemon.rs
- src/grpc/dfdaemon_upload.rs
> feat: add rate limit of the upload speed in download piece

- Cargo.lock
- Cargo.toml
- src/bin/dfget/main.rs
- src/config/dfdaemon.rs
- src/grpc/dfdaemon_upload.rs
- src/task/mod.rs
- src/task/piece.rs
- src/task/piece_collector.rs
> feat: add rate limit to download server and upload server

- src/bin/dfdaemon/main.rs
- src/gc/mod.rs
- src/grpc/dfdaemon_download.rs
- src/storage/content.rs
- src/storage/mod.rs
- src/task/mod.rs
- src/task/piece.rs
> feat: hard_link or copy to output path

- Cargo.lock
- Cargo.toml
- src/bin/dfget/main.rs
- src/grpc/dfdaemon_download.rs
- src/storage/content.rs
- src/storage/metadata.rs
> feat: if hardlink failed, remove the file and copy to output path

- Cargo.lock
- Cargo.toml
- src/proxy/mod.rs
> feat: add proxy to dfdaemon

- Cargo.lock
- Cargo.toml
- src/bin/dfdaemon/main.rs
- src/config/dfdaemon.rs
- src/proxy/mod.rs
> feat: add proxy config to dfdaemon

- Cargo.toml
- src/bin/dfdaemon/main.rs
- src/proxy/mod.rs
> feat: handle http request to remote server directly

- src/proxy/mod.rs
> feat: shutdown proxy service and fix proxy http request directly

- src/proxy/mod.rs
> feat: enable upgrade in http builder to support higher-level HTTP upgrades

- Cargo.lock
- src/utils/http.rs
> feat: add get_content_length function

- Cargo.lock
- Cargo.toml
- src/bin/dfget/main.rs
- src/gc/mod.rs
- src/grpc/dfdaemon_download.rs
- src/grpc/dfdaemon_upload.rs
- src/storage/metadata.rs
- src/storage/mod.rs
- src/task/mod.rs
- src/task/piece.rs
- src/utils/http.rs
> feat: refresh header and add response_header to response

- Cargo.lock
- Cargo.toml
- src/bin/dfget/main.rs
- src/grpc/dfdaemon_download.rs
- src/task/mod.rs
> feat: rename header to request_header in Download

- src/task/mod.rs
- src/task/piece.rs
> feat: return result directly

- src/storage/content.rs
- src/storage/mod.rs
- src/task/mod.rs
> feat: implement download task into async read

- src/task/piece.rs
> feat: remove download_from_source and download_from_remote_peer with async read

- Cargo.lock
- Cargo.toml
- src/bin/dfget/main.rs
- src/grpc/dfdaemon_download.rs
- src/proxy/mod.rs
- src/utils/id_generator.rs
> feat: replace filters with filtered_query_params

- src/lib.rs
- src/proxy/mod.rs
> feat: copy reader to proxy response

- Cargo.lock
- Cargo.toml
- src/bin/dfget/main.rs
- src/grpc/dfdaemon_download.rs
- src/proxy/mod.rs
- src/storage/metadata.rs
- src/task/mod.rs
- src/utils/http.rs
> feat: implement DownloadTaskResponse with multi responses

- Cargo.lock
- Cargo.toml
- src/grpc/dfdaemon_upload.rs
- src/proxy/mod.rs
- src/storage/content.rs
- src/storage/mod.rs
- src/task/mod.rs
- src/task/piece.rs
> feat: implement copy range reader to http response

- src/bin/dfget/main.rs
> feat: change short of the output options from o to O

- Cargo.lock
- Cargo.toml
- src/bin/dfget/main.rs
- src/proxy/mod.rs
- src/task/mod.rs
> feat: remove task finished response

- src/proxy/mod.rs
> feat: async write data to response

- src/proxy/mod.rs
> feat: optimize proxy request by dfdaemon

- src/proxy/mod.rs
> feat: optimize logs of th copy piece actions

- src/proxy/mod.rs
- src/task/piece.rs
> fix: calculate interested pieces by range

- src/proxy/mod.rs
- src/storage/content.rs
- src/task/piece.rs
- src/utils/http.rs
> fix: caculate range length of range header

- src/config/dfdaemon.rs
- src/proxy/mod.rs
- src/utils/tls.rs
> feat: add tunnel to handle https and add ca_cert and ca_key config

- src/proxy/mod.rs
> feat: handle the upgraded request with https

- src/proxy/mod.rs
- src/utils/tls.rs
> feat: change proxy https port to 443

- Cargo.lock
- Cargo.toml
- src/grpc/dfdaemon_download.rs
> feat: add leave host to dfdaemon

- Cargo.toml
> chore: update cargo version to v0.1.14

- Cargo.lock
- src/utils/tls.rs
> feat: generate CA by openssl with PEM foramt files

- src/proxy/mod.rs
> feat: remove error log about proxy directly to remote server

- src/config/dfdaemon.rs
- src/proxy/mod.rs
> feat: add registry mirror for dfdaemon

- src/config/dfdaemon.rs
- src/lib.rs
- src/proxy/mod.rs
> feat: rewrite registry mirror request

- Cargo.lock
- Cargo.toml
- src/bin/dfget/main.rs
- src/grpc/dfdaemon_download.rs
- src/lib.rs
- src/proxy/mod.rs
- src/task/mod.rs
> feat: if download back-to-source failed, proxy returns http code and header

- Cargo.lock
- Cargo.toml
- src/proxy/mod.rs
> feat: replace hyper-tls with hyper-rustls for HttpsConnector

- Cargo.lock
- Cargo.toml
- src/bin/dfget/main.rs
- src/config/dfdaemon.rs
- src/proxy/mod.rs
- src/utils/tls.rs
> feat: add self-signed certs for registry

- Cargo.lock
- Cargo.toml
- src/bin/dfget/main.rs
- src/proxy/mod.rs
> feat: add certificate chain for download request for self-signed certificate

- Cargo.lock
- Cargo.toml
> chore: update crate version to 0.1.15

- Cargo.toml
> chore: update crate versin to v0.1.16

- Cargo.lock
- src/backend/http.rs
- src/proxy/mod.rs
- src/task/mod.rs
- src/task/piece.rs
> feat: remove client certs for backend

- src/bin/dfget/main.rs
> fix: replace dragonfly_client::Error with dragonfly_client_core::Error

- Cargo.lock
- Cargo.toml
- Dockerfile
- dragonfly-client-config/Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-config/src/dfget.rs
- dragonfly-client-config/src/dfstore.rs
- dragonfly-client-config/src/lib.rs
- src/announcer/mod.rs
- src/bin/dfdaemon/main.rs
- src/bin/dfget/main.rs
- src/bin/dfstore/main.rs
- src/dynconfig/mod.rs
- src/gc/mod.rs
- src/grpc/dfdaemon_upload.rs
- src/lib.rs
- src/metrics/mod.rs
- src/proxy/header.rs
- src/proxy/mod.rs
- src/storage/mod.rs
- src/task/mod.rs
- src/task/piece.rs
- src/task/piece_collector.rs
> refactor: add dragonfly-client-config crate

- Cargo.lock
- Cargo.toml
- Dockerfile
- dragonfly-client-config/Cargo.toml
- dragonfly-client-storage/Cargo.toml
- dragonfly-client-storage/src/content.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- src/bin/dfdaemon/main.rs
- src/gc/mod.rs
- src/grpc/dfdaemon_upload.rs
- src/lib.rs
- src/task/mod.rs
- src/task/piece.rs
- src/task/piece_collector.rs
> refactor: add dragonfly-client-storage crate

- Cargo.lock
- Cargo.toml
- Dockerfile
- dragonfly-client-backend/Cargo.toml
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/lib.rs
- src/bin/dfdaemon/main.rs
- src/lib.rs
- src/task/mod.rs
- src/task/piece.rs
> refactor: add dragonfly-client-backend crate

- Cargo.toml
- Dockerfile
> chore: remove src dir in Dockerfile

- Cargo.lock
> chore: update crate verison

- .github/workflows/release.yml
> chore: free disk space in actions

- dragonfly-client-backend/Cargo.toml
- dragonfly-client-config/Cargo.toml
- dragonfly-client-storage/Cargo.toml
- dragonfly-client-util/Cargo.toml
> chore: remove readme in sub crates

- dragonfly-client-storage/src/content.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/task/mod.rs
> feat: add empty task handler for hard_link_or_copy

- Cargo.toml
> chore: update Cargo version to v0.1.19

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
> chore: add rust cache in actions

- .github/workflows/release.yml
> fix: rust cache in release actions

- Cargo.toml
> chore: update crate verison to v0.1.20

- .github/workflows/docker.yml
> chore: move cache for buildx in docker actions

- .github/workflows/release.yml
- Cargo.toml
> chore: clean disk in release actions

- .github/workflows/release.yml
> feat: remove tool cache

- .github/workflows/release.yml
> feat: remove haskell and large-packages in clean-disk

- .github/workflows/release.yml
> feat: remove rust cache steps

- .github/workflows/release.yml
> feat: remove free disk space in publish

- .github/workflows/release.yml
> chore: optimize release actions

- .github/workflows/release.yml
> chore: add libclang-dev to release actions

- .github/workflows/docker.yml
- .github/workflows/release.yml
> chore: remove tips in actions

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-storage/src/content.rs
- dragonfly-client/src/proxy/mod.rs
> feat: add read buffer to io::copy

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/proxy/mod.rs
> chore: update api into v2.0.106

- .github/workflows/release.yml
> chore: add disk clean in publish release action

- .github/workflows/release.yml
> chore: add libclang-dev library in publish actions

- dragonfly-client/src/task/mod.rs
> feat: report piece metadata to scheduler in spawn

- dragonfly-client-init/Dockerfile
- dragonfly-client/Dockerfile
> chore: add workspace depends to Dockerfile

- Cargo.lock
- Cargo.toml
> chore: update version to v0.1.24

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfinit.rs
- dragonfly-client-init/Cargo.toml
- dragonfly-client-init/src/bin/main.rs
- dragonfly-client/Cargo.toml
> feat: add containerd field to container runtime configuration

- Cargo.lock
- Cargo.toml
- dragonfly-client-init/Cargo.toml
- dragonfly-client-init/src/bin/main.rs
- dragonfly-client-init/src/container_runtime/containerd.rs
- dragonfly-client-init/src/container_runtime/mod.rs
- dragonfly-client-init/src/lib.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
> feat: add init_tracing to dfinit

- dragonfly-client-config/src/dfinit.rs
> feat: add config_path for containerd

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-core/Cargo.toml
- dragonfly-client-core/src/lib.rs
- dragonfly-client-init/Cargo.toml
- dragonfly-client-init/src/bin/main.rs
- dragonfly-client-init/src/container_runtime/containerd.rs
- dragonfly-client-init/src/container_runtime/mod.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
> feat: parse containerd config by toml

- Cargo.lock
- Cargo.toml
- dragonfly-client-core/Cargo.toml
- dragonfly-client-core/src/lib.rs
- dragonfly-client-init/Cargo.toml
- dragonfly-client-init/src/bin/main.rs
- dragonfly-client-init/src/container_runtime/containerd.rs
> feat: when contaienrd use old version, dfinit updates the mirror config

- .github/workflows/docker.yml
> fix: change docker build timeout and fix release ci

- dragonfly-client-storage/src/content.rs
> feat: add truncate options to content for writing piece

- dragonfly-client-config/src/dfinit.rs
- dragonfly-client-init/src/container_runtime/containerd.rs
- dragonfly-client/src/proxy/header.rs
- dragonfly-client/src/proxy/mod.rs
> feat: support config_path mirror for containerd

- dragonfly-client-config/src/dfinit.rs
- dragonfly-client-init/src/container_runtime/docker.rs
- dragonfly-client-init/src/container_runtime/mod.rs
> feat: add docker config for dfinit

- Cargo.lock
- Cargo.toml
> chore: update verison to v0.1.25

- Cargo.lock
- Cargo.toml
- dragonfly-client-init/src/container_runtime/containerd.rs
> fix: if plugins key is not exist, dfinit can not find index in containerd

- .github/workflows/docker.yml
> chore: split push client image and push dfinit image in actions

- dragonfly-client-storage/src/metadata.rs
> feat: change memtable memory limit in rocksdb

- dragonfly-client-config/src/dfinit.rs
- dragonfly-client-init/src/container_runtime/containerd.rs
- dragonfly-client-init/src/container_runtime/crio.rs
- dragonfly-client-init/src/container_runtime/docker.rs
- dragonfly-client-init/src/container_runtime/mod.rs
> feat: optimize enum for container runtime

- dragonfly-client-init/src/container_runtime/containerd.rs
> feat: if registry is not set, create config_path for contianerd

- Cargo.lock
- Cargo.toml
> chore: update version to v0.1.27

- dragonfly-client/Dockerfile
> chore: add ca-certificates package to client dockerfile

- Cargo.toml
- dragonfly-client-backend/src/http.rs
> feat: add native tls for backend client

- Cargo.lock
- Cargo.toml
> chore: update version to v0.1.28

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/task/piece_collector.rs
> feat: add prefetch feature for proxy server

- Cargo.lock
- Cargo.toml
> chore: update version to v0.1.29

- CONTRIBUTING.md
- README.md
> docs: fix typo in README.md

- Cargo.lock
- Cargo.toml
> chore: update version to v0.1.30

- dragonfly-client/src/proxy/mod.rs
> feat: add logs for generate cert

- Cargo.lock
- dragonfly-client-backend/Cargo.toml
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/lib.rs
- dragonfly-client/src/task/piece.rs
> unittest: improve code coverage

- dragonfly-client-storage/src/metadata.rs
Wraps most of the redundant rocksdb transaction operations in two new helper functions, `with_txn` and `transactional_update_or_else`.
This is the first step of extracting rocksdb logic and adding a db-agnostic layer for client-storage.
> Refactor: wrap rocksdb transaction operations in closures

- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/task/piece.rs
> feat: add error log for grpc handler

- Cargo.lock
- dragonfly-client-backend/Cargo.toml
- dragonfly-client-backend/src/lib.rs
- dragonfly-client-core/Cargo.toml
- dragonfly-client-core/src/error/errors.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/task/mod.rs
- dragonfly-client/src/task/piece.rs
> feat: support plugin feature for backend

- dragonfly-client-init/Dockerfile
- dragonfly-client/Dockerfile
> chore: add plugin Cargo.yaml to Dockerfile

- dragonfly-client/Dockerfile
> chore: add curl for client Dockerfile

- Cargo.toml
- dragonfly-client/Dockerfile
> chore: add apache2-utils to Dockerfile

- Cargo.lock
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client-storage/src/storage_engine/mod.rs
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
> chore: add License for storage_engine

- dragonfly-client-config/src/dfdaemon.rs
> fix: typo in dfdaemon.rs

- .gitignore
> chore: change gitignore for vendor

- rust-toolchain.toml
> chore: change rust-toolchain to 1.75.0 to match Dockerfile build image

- Cargo.lock
- Cargo.toml
> chore: update cargo version to v0.1.36

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/content.rs
> fix: hardlink failed when file is not exists

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
> feat: remove await when download task

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client/src/task/mod.rs
> fix: semaphore to limit spawn 

- dragonfly-client/src/grpc/scheduler.rs
> feat: optimize log of th available schedulers

- dragonfly-client/Dockerfile
> chore: add tools for dfdaemon container

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/lib.rs
- dragonfly-client/src/stats/mod.rs
> feat: add profiling to dfdaemon

- .github/workflows/docker.yml
- Cargo.lock
- dragonfly-client/Cargo.toml
> chore: add free disk in actions

- dragonfly-client/src/grpc/mod.rs
> feat: optimize grpc log

- dragonfly-client/Cargo.toml
> feat: add stats and background_threads features for jemalloc

- dragonfly-client/src/grpc/scheduler.rs
> feat: ToString replaces with Display

- dragonfly-client/Dockerfile
> chore: add llvm for container

- Cargo.lock
- Cargo.toml
> chore: update crate version

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/build.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/mod.rs
- dragonfly-client/src/metrics/mod.rs
- dragonfly-client/src/task/mod.rs
- dragonfly-client/src/task/piece.rs
> feat: add metrics for dfdaemon

- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client/src/announcer/mod.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/gc/mod.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/task/mod.rs
> feat: leave host and peer from scheduler

- dragonfly-client-init/Dockerfile
- dragonfly-client/Dockerfile
> chore: add build.rs to Dockerfile

- dragonfly-client/Dockerfile
> chore: optimize rumtime Dockerfile

- dragonfly-client/Dockerfile
> chore: add wget for runtime Dockerfile

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/task/mod.rs
- dragonfly-client/src/task/piece.rs
> feat: collect traffic metrics by fake download piece

- Cargo.lock
- Cargo.toml
- dragonfly-client/Dockerfile
- dragonfly-client/build.rs
> feat: add git for build Dockerfile for generating commit hash

- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
> feat: print content length for downloading task

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/metadata.rs
> fix: add rollback for with_txn

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/metadata.rs
> fix: transaction memory leak storage engine

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
> fix: txn memory leak in storage

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
> feat: replace TransactionDB with DB

- dragonfly-client-config/src/dfdaemon.rs
> feat: change read_buffer_size and write_buffer_size

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/proxy/mod.rs
> feat: change connection buffer size to 2KB in hyper server

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
- dragonfly-client/src/proxy/mod.rs
> feat: write sync for rocksdb

- dragonfly-client/src/bin/dfdaemon/main.rs
> feat: change the size of log max files

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
> feat: change prefix_extractor to 128

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
> feat: set set_total_order_seek true

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/task/mod.rs
> feat: only prefetch once

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
> feat: optimize default params for concurrent

- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
> feat: if the task is already prefetched, ignore the error

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
- dragonfly-client/src/task/mod.rs
> feat: use set_total_order_seek to skip bloom filter

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client/src/gc/mod.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/task/mod.rs
> feat: if task download failed change the metadata

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client/src/gc/mod.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/scheduler.rs
- dragonfly-client/src/task/mod.rs
> feat: add leave task and remove task finished only download from local

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/task/mod.rs
- dragonfly-client/src/task/piece_collector.rs
> feat: add log for connecting with scheduler

- dragonfly-client-storage/src/metadata.rs
- dragonfly-client/src/gc/mod.rs
> feat: define task is_expired  by upload_at

- dragonfly-client-config/src/dfinit.rs
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client-init/src/container_runtime/crio.rs
- dragonfly-client-util/src/digest/mod.rs
- dragonfly-client-util/src/http/mod.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/metrics/mod.rs
- dragonfly-client/src/proxy/mod.rs
I found some typos while reading the code.
> chore: fix typo

- .github/workflows/ci.yml
> chore: update codecov action version

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/tracing/mod.rs
> feat: add suffix for log file

- Cargo.toml
- dragonfly-client/src/dynconfig/mod.rs
> feat: find the available scheduler cluster by dynconfig

- Cargo.lock
- dragonfly-client/src/grpc/mod.rs
> feat: change connect timeout to 1s

- Cargo.lock
- Cargo.toml
- dragonfly-client/Cargo.toml
- dragonfly-client/src/tracing/mod.rs
> feat: redirect stderr to stderr log file

- .github/workflows/ci.yml
> chore: change codecov version

- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/bin/dfstore/main.rs
- dragonfly-client/src/tracing/mod.rs
> feat: change tracing rotation to DAILY

- Cargo.lock
- Cargo.toml
- dragonfly-client/Cargo.toml
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/bin/dfstore/main.rs
- dragonfly-client/src/tracing/mod.rs
> feat: replace appender rolling with rolling file

- dragonfly-client/src/metrics/mod.rs
- dragonfly-client/src/proxy/mod.rs
> feat: add proxy request metrics

- Cargo.lock
- Cargo.toml
- dragonfly-client-backend/Cargo.toml
- dragonfly-client-backend/src/http.rs
- dragonfly-client-util/Cargo.toml
- dragonfly-client-util/src/tls/mod.rs
- dragonfly-client/src/proxy/mod.rs
> feat: support proxy HTTPS from nydus

- dragonfly-client-config/src/dfcache.rs
- dragonfly-client-config/src/lib.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/Dockerfile
- dragonfly-client/src/bin/dfcache/main.rs
> feat: add dfcache command for d7y

- Cargo.lock
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/lib.rs
- dragonfly-client-core/Cargo.toml
- dragonfly-client-core/src/error/errors.rs
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-util/src/http/mod.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/task/mod.rs
- dragonfly-client/src/task/piece.rs
> feat: add error log for backend

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/task/mod.rs
- dragonfly-client/src/task/piece.rs
- dragonfly-client/src/task/piece_collector.rs
> feat: remove rocksdb bloom filter

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/task/mod.rs
- dragonfly-client/src/task/piece.rs
- dragonfly-client/src/task/piece_collector.rs
> feat: merge finished piece and remove finished piece

- dragonfly-client/src/task/mod.rs
> feat: optimize download all pieces log

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
> feat: set fill cache is false

- dragonfly-client/src/proxy/mod.rs
> feat: record the proxy request started metrics

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/task/piece.rs
> feat: call download_piece_failed when piece download failed

- Cargo.lock
- Cargo.toml
- dragonfly-client/Cargo.toml
- dragonfly-client/src/tracing/mod.rs
> feat: set ChronoLocal for tracing

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
> feat: wait for piece finished before update piece metadata

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
> feat: add prefetch log for downloading

- dragonfly-client/src/grpc/scheduler.rs
> feat: skip all label in announce_peer

- dragonfly-client-config/src/dfdaemon.rs
> feat: change default value of keep storage to false

- .github/workflows/release.yml
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/main.rs
- dragonfly-client/src/bin/dfcache/remove.rs
- dragonfly-client/src/bin/dfcache/stat.rs
> feat: add args to dfcache command

- Cargo.lock
- dragonfly-client-util/Cargo.toml
- dragonfly-client-util/src/id_generator/mod.rs
> feat: add cache_task_id and cache_peer_id to id generater

- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
> feat: add cache_task implements in storage

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/grpc/scheduler.rs
> feat: add cache_peer apis and cache_task apis for scheduler client

- .github/workflows/ci.yml
> chore: add verbose for codecov actions

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/announcer/mod.rs
Add interval field to AnnounceHostRequest, so that scheduler can detect peer survivability and clear offline peer metadata.
https://github.com/dragonflyoss/Dragonfly2/issues/3350
> feat: add interval field to AnnounceHostRequest

- rust-toolchain.toml
> chore: update rust-toolchain version

- Cargo.lock
- Cargo.toml
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client-storage/Cargo.toml
- dragonfly-client-storage/src/content.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
- dragonfly-client-util/Cargo.toml
- dragonfly-client-util/src/digest/mod.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/main.rs
- dragonfly-client/src/bin/dfcache/remove.rs
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/resource/cache_task.rs
- dragonfly-client/src/resource/mod.rs
> feat: add import subcommand

- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
> feat: add progress bar for dfcache import

- dragonfly-client-util/src/id_generator/mod.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/mod.rs
- dragonfly-client/src/metrics/mod.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
> feat: add metrics for dfcache

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/gc/mod.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/scheduler.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/cache_task.rs
- dragonfly-client/src/resource/task.rs
> feat: add import feature in client

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/gc/mod.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/scheduler.rs
- dragonfly-client/src/metrics/mod.rs
- dragonfly-client/src/resource/cache_task.rs
- dragonfly-client/src/resource/task.rs
> feat: add stat_cache_task and delete_cache_task features

- .github/workflows/ci.yml
> chore: change codecov vesion and delete fail_ci_if_error field

- dragonfly-client/src/bin/dfdaemon/main.rs
> feat: drop cache_task when client shutdown

- dragonfly-client-backend/src/http.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/piece_collector.rs
> feat: optimize log for piece id with tracing instrument

- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/mod.rs
> feat: optimize gpc server config for dfdaemon

- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/mod.rs
- dragonfly-client/src/resource/piece_collector.rs
> Fix that there are no other competing changes to the value of the same key in DashMap

- dragonfly-client/src/resource/piece_collector.rs
> feat: lock interested_piece in collector

- Cargo.lock
- Cargo.toml
- dragonfly-client-backend/Cargo.toml
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/lib.rs
- dragonfly-client-backend/src/oss.rs
- dragonfly-client-core/Cargo.toml
- dragonfly-client-core/src/error/errors.rs
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
> refactor: oss implements in backend

- Cargo.lock
- Cargo.toml
- dragonfly-client-backend/src/http.rs
> feat: change http test dependencies in backend

- Cargo.lock
- Cargo.toml
- dragonfly-client/Cargo.toml
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/resource/cache_task.rs
> feat: implement stat command for cache task

- dragonfly-client/src/bin/dfcache/remove.rs
> feat: implement remove cache task in dfcache

- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/resource/cache_task.rs
> feat: rename create_persistent_cache_task to create_persistent in cache_task

- dragonfly-client/src/bin/dfget/main.rs
> feat: remove the logic of starting dfdaemon when dfget downloads file

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
> feat: remove lock file from dfdaemon

- Cargo.lock
- dragonfly-client/Cargo.toml
- dragonfly-client/src/bin/dfget/main.rs
> feat: parse output path to absolute path

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/content.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/main.rs
- dragonfly-client/src/bin/dfcache/remove.rs
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/resource/cache_task.rs
> feat: implement export in dfcache

- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/gc/mod.rs
- dragonfly-client/src/resource/cache_task.rs
> feat: add garbage collection for cache task

- Cargo.lock
- Cargo.toml
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/lib.rs
- dragonfly-client-backend/src/object_storage.rs
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client-util/src/http/mod.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/bin/dfget/main.rs
> refactor: download directory from object storage

- dragonfly-client-core/src/error/errors.rs
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client/src/bin/dfget/main.rs
This PR is done by finishing the following tasks:
Check the path before starting the download task could save the network resource.
> feat: add check before starting the download task

- dragonfly-client-core/src/error/errors.rs
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/remove.rs
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/bin/dfget/main.rs
> feat: add validate_args for dfget and dfcache

- dragonfly-client/src/resource/task.rs
> feat: rename task_result to task

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/task.rs
> feat: if HTTP get the BackendError of the response, return BackendError to proxy

- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/resource/cache_task.rs
- dragonfly-client/src/resource/task.rs
> feat: if download back-to-source failed, abort all jobs

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/bin/dfcache/remove.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/health.rs
- dragonfly-client/src/grpc/manager.rs
- dragonfly-client/src/grpc/mod.rs
- dragonfly-client/src/grpc/scheduler.rs
- dragonfly-client/src/grpc/security.rs
- rust-toolchain.toml
> feat: add request timeout for connection

- dragonfly-client/src/metrics/mod.rs
> feat: add warn logs when handle level1 task task slowly

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/metrics/mod.rs
> fix: download too long logs

- Cargo.lock
- dragonfly-client/Cargo.toml
- dragonfly-client/src/announcer/mod.rs
> refactor: disk information in announcer module

- Cargo.lock
- Cargo.toml
- dragonfly-client-init/src/container_runtime/containerd.rs
Fixes https://github.com/dragonflyoss/Dragonfly2/issues/3372
> feat: add header for mirror mode

- .github/workflows/ci.yml
- .github/workflows/docker.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- ci/Dockerfile
- dragonfly-client-config/src/dfinit.rs
> chore: add self-hosted larger runers

- dragonfly-client/src/proxy/mod.rs
> feat: if host is not exist, set host

- dragonfly-client-init/src/bin/main.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
- dragonfly-client/src/bin/dfcache/main.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/bin/dfstore/main.rs
- dragonfly-client/src/gc/mod.rs
- dragonfly-client/src/tracing/mod.rs
> feat: remove is_uploading condition in gc

- dragonfly-client-storage/src/metadata.rs
- dragonfly-client/src/resource/task.rs
> feat: add log for deleting piece

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
> feat: add zstd compression for grpc

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
> feat: when send to scheduler failed, join_set detach all task

- Cargo.lock
- Cargo.toml
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/lib.rs
- dragonfly-client-config/src/lib.rs
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client-util/src/id_generator/mod.rs
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/remove.rs
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/header.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/cache_task.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
> feat: calculate piece length by file length

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-util/src/id_generator/mod.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/resource/task.rs
> feat: filter query params

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client-storage/src/storage_engine/mod.rs
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/resource/piece.rs
> feat: optimize gc with rocksdb

- dragonfly-client/src/resource/task.rs
> feat: add piece length for download request

- Cargo.toml
- dragonfly-client/src/grpc/dfdaemon_upload.rs
> feat: add with_capacity for content

- Cargo.lock
- dragonfly-client-backend/examples/plugin/src/lib.rs
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/lib.rs
- dragonfly-client-backend/src/object_storage.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/metrics/mod.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
> feat: add metrics of the backend request

- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/metrics/mod.rs
> feat: add disk space metric

- Cargo.lock
- Cargo.toml
- ci/Dockerfile
- ci/Dockerfile.dfinit
> chore: fix 'as' keyword should match the case of the 'from' keyword

- Cargo.toml
- dragonfly-client-storage/src/lib.rs
> feat: add log for deleting task

- Cargo.lock
- dragonfly-client-init/src/container_runtime/mod.rs
- dragonfly-client-util/Cargo.toml
- dragonfly-client-util/src/digest/mod.rs
Implemented the digest crc32 algorithm with some ut
> add crc32 algorithm with few tests

- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/object_storage.rs
> test: format unit test in backend

- ci/Dockerfile
> fix: key/value format with whitespace separator should not be used

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
> feat: set prefix_extractor for column families

- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
Add `get_pieces()` and fix unit tests about prefix iteration.
> feat: add get_pieces() and fix unit tests

- dragonfly-client-storage/src/metadata.rs
> test: remove metadata mock const

- ci/Dockerfile
- ci/Dockerfile.dfinit
> chore: update build image and golang image

- dragonfly-client/src/grpc/dfdaemon_upload.rs
> feat: replace read_exact with read_to_end in download_piece

- dragonfly-client-backend/src/object_storage.rs
- dragonfly-client/src/bin/dfget/main.rs
> feat: optimize operator of the object_storage

- dragonfly-client/src/bin/dfget/main.rs
> fix: --storage-credential-path in dfget description

- Cargo.toml
- dragonfly-client-backend/Cargo.toml
- dragonfly-client-backend/src/lib.rs
- dragonfly-client-util/Cargo.toml
> refactor: backend tests in lib.rs

- dragonfly-client/src/grpc/dfdaemon_upload.rs
> feat: when send piece error drop out_stream_tx

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/cache_task.rs
- dragonfly-client/src/resource/piece_collector.rs
- dragonfly-client/src/resource/task.rs
>  feat: add interrupt for download from remote peers

- .github/workflows/release.yml
> chore: add timeout-minutes for release actions

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/mod.rs
- dragonfly-client/src/proxy/mod.rs
> feat: proxy reuses the dfdaemon_download_client

- dragonfly-client-backend/src/object_storage.rs
> feat: optimize make_need_fields_message macro

- dragonfly-client/src/proxy/mod.rs
> feat: add log for generate certs

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/proxy/mod.rs
> feat: print log for tls failed

- dragonfly-client-config/src/dfinit.rs
- dragonfly-client-init/src/container_runtime/containerd.rs
> feat: support ca and skip_verify for containerd registry and remove mirror mode for containerd old version

- dragonfly-client-backend/src/http.rs
- dragonfly-client/src/resource/piece.rs
> Fix: Comment for Storage in piece.rs is wrong

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/proxy/header.rs
- dragonfly-client/src/proxy/mod.rs
> feat: add X-Dragonfly-Use-P2P header for proxy to use P2P to distribute the content

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-storage/src/content.rs
- dragonfly-client/src/announcer/mod.rs
> feat: announce disable shared for scheduler

- dragonfly-client-storage/src/content.rs
> feat: add log for deleting task content

- dragonfly-client/src/bin/dfget/main.rs
> test: refactor tests in dfget

- Cargo.lock
- Cargo.toml
> chore: update crate verison to v0.1.109

- Cargo.toml
> feat: optimize the profile release for binary

- .github/workflows/docker.yml
- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/content.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
- dragonfly-client-util/src/id_generator/mod.rs
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/remove.rs
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/gc/mod.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/scheduler.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/mod.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
> feat: rename cache task to persistent cache task

- Cargo.lock
- Cargo.toml
- ci/Dockerfile
- ci/Dockerfile.dfinit
- dragonfly-client/src/announcer/mod.rs
> feat: add upload_rate_limit and download_rate_limit for announcer

- Cargo.toml
> chore: update client version to v0.1.110

- Cargo.lock
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/lib.rs
- dragonfly-client-config/Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-util/src/tls/mod.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
> feat: load certs in dfdaemon config

- Cargo.lock
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-core/Cargo.toml
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/piece_collector.rs
> feat: add ServerTlsConfig and ClientTlsConfig for upload service

- dragonfly-client/src/grpc/manager.rs
> test: fixed invalid_uri_should_fail in manager grpc

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client/src/grpc/manager.rs
> feat: add health check for manager addr

- Cargo.lock
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-core/Cargo.toml
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client-util/Cargo.toml
- dragonfly-client-util/src/http/basic_auth.rs
- dragonfly-client-util/src/http/mod.rs
- dragonfly-client/src/proxy/mod.rs
> feat: add basic auth for HTTP proxy

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/proxy/header.rs
- dragonfly-client/src/proxy/mod.rs
> feat: support X-Dragonfly-Prefetch header to control prefetching

- dragonfly-client-storage/src/content.rs
- dragonfly-client/src/gc/mod.rs
3 characters of task id => 16^3 => 4096
> feat: storage needs split by the first 3 characters of task id(sha256) to avoid too many files in one directory

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/Cargo.toml
- dragonfly-client-config/src/lib.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/metrics/mod.rs
> feat: remove lazy_static for getting build env

- Cargo.lock
- Cargo.toml
- dragonfly-client-core/Cargo.toml
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/announcer/mod.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/gc/mod.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
> feat: add tonic-reflection sever error for ClientError

- Cargo.lock
- Cargo.toml
- dragonfly-client-util/src/id_generator/mod.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
> feat: exclude digest when calculating task id

- ci/Dockerfile
This pull request includes updates to the `ci/Dockerfile` to streamline the Docker image setup process. The changes primarily involve updating the base images and refining the package installation commands.
Updates to Docker image setup:
* [`ci/Dockerfile`](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL1-R5): Updated the Rust base image to use a more flexible version tag (`rust:1.80`).
* [`ci/Dockerfile`](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL1-R5): Modified the package installation command to use `--no-install-recommends` to minimize the image size and reduce potential bloat.
* [`ci/Dockerfile`](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL51-R51): Updated the Golang base …
> Refactor(deps)  update rust and golang versions in dockerfile

- ci/Dockerfile
Reverts dragonflyoss/client#804
> Revert "Refactor(deps)  update rust and golang versions in dockerfile"

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/announcer/mod.rs
- dragonfly-client/src/gc/mod.rs
- dragonfly-client/src/health/mod.rs
- dragonfly-client/src/metrics/mod.rs
- dragonfly-client/src/stats/mod.rs
> fix: shutdown repeatedly during gc

- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
> feat: delete metadata and content of the persistent cache task

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/resource/persistent_cache_task.rs
- dragonfly-client/src/resource/piece.rs
> feat: add content_length, digest and piece_count for UploadPersistentCacheTaskStartedRequest

- dragonfly-client-util/src/http/basic_auth.rs
- dragonfly-client-util/src/http/mod.rs
> test: add ut for client-util

- dragonfly-client-util/src/tls/mod.rs
> test: add ut for client-util/tls

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client/src/gc/mod.rs
Fixed https://github.com/dragonflyoss/Dragonfly2/issues/3633.
> feat: when the task is downloading, it is not allowed to delete the task

- dragonfly-client-init/src/container_runtime/crio.rs
This pull request introduces a new test module for the `CRIO` implementation in the `dragonfly-client-init` project. The test ensures that the `CRIO` configuration is correctly written to a file.
Testing enhancements:
* Added a new test module with an asynchronous test function `test_crio_config` to verify the `CRIO` configuration setup.
> test(crio): add unit test for CRIO config

- dragonfly-client/src/metrics/mod.rs
> feat: add reset handler for metrics

- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
> feat: optimize generater of the piece id

- dragonfly-client/src/proxy/mod.rs
> feat: optimize find_matching_rule func

- dragonfly-client-storage/src/storage_engine/rocksdb.rs
- dragonfly-client/src/tracing/mod.rs
> feat: remove fill_cache from getting in rocksdb

- Cargo.lock
- Cargo.toml
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/object_storage.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-util/src/http/mod.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/task.rs
> feat: remove unnecessary logs

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/announcer/mod.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/metrics/mod.rs
- dragonfly-client/src/proxy/mod.rs
> feat: add disk bandwidth for metrics and announcer

- dragonfly-client/src/metrics/mod.rs
> feat: rename disk_read_bandwidth to disk_read_bytes

- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/mod.rs
- dragonfly-client/src/proxy/mod.rs
This pull request includes several changes to the `dragonfly-client` to enhance the gRPC server and client configurations, as well as some code refactoring. The most important changes include adding a barrier for server startup synchronization, enabling TCP and HTTP2 keepalive settings, and reducing the gRPC request timeout.
Enhancements to gRPC server and client configurations:
* Added a `Barrier` for server startup synchronization in `DfdaemonDownloadServer` and `DfdaemonUploadServer`. (`dragonfly-client/src/grpc/dfdaemon_download.rs`, `dragonfly-client/src/grpc/dfdaemon_upload.rs`) [[1]](diffhunk://#diff-303fb9e5802b43f6e4657a81ed3ea511a911a64d8bf32abb0d1bea5cc127498dL108-R108) [[2]](diffhunk://#diff-ee96a329b9be744aa8bbeb4c7c8936c29ba529c4a4e51778ca7bfd31684c26a1L106-R106)
* Enabled …
> feat: reuse the tonic uds client in proxy

- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/lib.rs
> feat: reuse http client for backend

- dragonfly-client-backend/src/lib.rs
- dragonfly-client-backend/src/object_storage.rs
> feat: reuse http client for object storage in backend

- dragonfly-client-backend/src/hdfs.rs
> feat: add timeout for hdfs backend

- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/resource/task.rs
> fix: barrier blocks thread

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-storage/src/content.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/scheduler.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
- dragonfly-client/src/resource/piece_collector.rs
- dragonfly-client/src/resource/task.rs
This pull request includes several updates and improvements to the `dragonfly-client` project. The most important changes involve version updates in `Cargo.toml`, buffer size adjustments, and various code improvements for better performance and readability.
* Updated the version of `dragonfly-client` dependencies from `0.1.117` to `0.1.118` in `Cargo.toml`.
* Changed the default buffer sizes for reading and writing pieces to disk from 4KB to 128KB in `dragonfly-client-config/src/dfdaemon.rs`.
* Adjusted the channel buffer sizes from `1024 * 10` to `10 * 1024` in various files for better performance. [[1]](diffhunk://#diff-303fb9e5802b43f6e4657a81ed3ea511a911a64d8bf32abb0d1bea5cc127498dL357-R357) [[2]](diffhunk://#diff-303fb9e5802b43f6e4657a81ed3ea511a911a64d8bf32abb0d1bea5cc127498dL746-R74 …
> fix: rocksdb panic caused by out of bounds

- ci/Dockerfile
- ci/Dockerfile.dfinit
- dragonfly-client-backend/src/hdfs.rs
- dragonfly-client-backend/src/object_storage.rs
- dragonfly-client-config/build.rs
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
- rust-toolchain.toml
This pull request includes several changes to update dependencies, enhance performance, and improve logging levels in the `dragonfly-client` project. The most important changes include updating the Rust version, adjusting buffer sizes, and modifying log levels for better debugging.
* [`ci/Dockerfile`](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL1-R1): Updated Rust version from `1.80.0` to `1.82.0`.
* [`ci/Dockerfile.dfinit`](diffhunk://#diff-4bc49af73ee4c312bbe45791f2bb95c950ecc719ca34b5bf59af0649db904dc5L1-R1): Updated Rust version from `1.80.0` to `1.82.0`.
* [`rust-toolchain.toml`](diffhunk://#diff-2b1bde2cf3a858b7bf7424cb8bcbf01f35b94dc80b925d9432cbab3319ca9b4eL2-R2): Changed Rust channel from `1.80.0` to `1.82.0`.
Performance …
> feat: add sse4.2 target feature for building

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client-util/src/id_generator/mod.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/metrics/mod.rs
- dragonfly-client/src/proxy/cache.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
This pull request introduces several changes to the Dragonfly client, focusing on adding LRU cache functionality to the proxy server and making various improvements and additions across different modules.
* Added a new `Cache` struct in `dragonfly-client/src/proxy/cache.rs` for storing HTTP responses using the LRU algorithm. This includes methods for creating a new cache, getting content by request, and adding pieces to the cache.
* Integrated the new `Cache` into the `Proxy` struct and its associated methods in `dragonfly-client/src/proxy/mod.rs`. This includes passing the cache to various handler functions and using it to manage piece content. [[1]](diffhunk://#diff-6421011d65f9faa2a693ea46e321cc00e07b77ef8792a1b795d1db98d9e5ec4cR75-R77) …
> feat: add cache store for proxy

- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/health.rs
- dragonfly-client/src/grpc/interceptor.rs
- dragonfly-client/src/grpc/manager.rs
- dragonfly-client/src/grpc/mod.rs
- dragonfly-client/src/grpc/scheduler.rs
This pull request includes changes to the `dragonfly-client` to rename the `tracing_grpc` module to `interceptor` and update all references accordingly. The most important changes include renaming the file, updating import paths, and modifying module declarations.
File renaming:
* [`dragonfly-client/src/grpc/interceptor.rs`](diffhunk://#diff-2ad070e1cd1a0873ef119dff254ee56c6a422f9ab62bc6bf821d42bd5289fa2cL1-R18): Renamed from `dragonfly-client/src/grpc/tracing_grpc.rs` and added the Apache License header.
Import path updates:
* [`dragonfly-client/src/grpc/dfdaemon_download.rs`](diffhunk://#diff-303fb9e5802b43f6e4657a81ed3ea511a911a64d8bf32abb0d1bea5cc127498dL65-R65): Updated import path from `tracing_grpc::TracingInterceptor` to `interceptor::TracingInterceptor`.
* …
> feat: rename tracing_grpc.rs to interceptor.rs

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
> chore: use gzip compress for building rpm and deb

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- dragonfly-client/Cargo.toml
> chore: add auto-req no for building rpm

- Cargo.lock
- Cargo.toml
- ci/dfdaemon.yaml
This pull request includes changes to update the version of multiple dependencies in the `Cargo.toml` file and to improve the configuration file `ci/dfdaemon.yaml` with additional settings and comments.
Dependency version updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15): Updated the version of `dragonfly-client` and its related dependencies from "0.1.122" to "0.1.123". [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31)
Configuration improvements:
* [`ci/dfdaemon.yaml`](diffhunk://#diff-6ae9e02b3c9316c7fd63bdc080bc80633e59659e9fb9327765e4b7d799d2e466L1-R71): Added comments to clarify …
> chore: change the default config for rpm and deb

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/mod.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
> feat: support the rate limit for preheat request

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
This pull request includes a version update for the `dragonfly-api` dependency in the `Cargo.toml` file.
Dependency update:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L33-R33): Updated `dragonfly-api` dependency from version `2.0.174` to `2.0.177`.
> chore: update api version to 2.0.177

- Cargo.lock
- Cargo.toml
This pull request includes updates to the `Cargo.toml` file, primarily focusing on version increments for various dependencies and a minor modification to the `tonic` dependency features.
* Updated the package version from `0.1.124` to `0.1.125`.
* Incremented the versions of the `dragonfly-client` dependencies from `0.1.124` to `0.1.125`.
Dependency feature modification:
* Removed the `zstd` feature from the `tonic` dependency.
> feat: remove zstd for tonic

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/mod.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/piece_downloader.rs
- dragonfly-client/src/resource/task.rs
This pull request introduces several changes to the `dragonfly-client` and `dragonfly-client-config` modules, focusing on adding a new piece downloader implementation and improving the error handling and configuration defaults.
* Added a new module `piece_downloader` to handle piece downloading with different protocols. This includes the `Downloader` trait, `DownloaderFactory`, and `GRPCDownloader` implementation. (`dragonfly-client/src/resource/piece_downloader.rs`)
* Introduced a new function `default_upload_protocol` to set the default protocol for the upload server to "grpc". (`dragonfly-client-config/src/dfdaemon.rs`)
* Updated the `UploadServer` struct to include a `protocol` field with a default value set by `default_upload_protocol`. (`dragonfly-client-config/src/dfdaemon.rs`)
* …
> feat: add downloader for downloading piece

- Cargo.lock
- Cargo.toml
> chore: update version to 0.2.0

- Cargo.lock
- Cargo.toml
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/lib.rs
- dragonfly-client-backend/src/object_storage.rs
- dragonfly-client-config/src/dfcache.rs
- dragonfly-client-config/src/dfget.rs
- dragonfly-client-init/src/bin/main.rs
- dragonfly-client-storage/src/content.rs
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/remove.rs
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/bin/dfstore/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/health.rs
- dragonfly-client/src/grpc/manager.rs
- dragonfly-client/src/grpc/mod.rs
- dragonfly-client/src/grpc/scheduler.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/piece_collector.rs
- dragonfly-client/src/resource/task.rs
This pull request includes several changes focused on improving error handling, updating dependencies, and adding new constants. The most important changes include replacing `map_err` with `inspect_err` for better error logging, updating the `dragonfly-api` dependency version, and adding default output file mode constants.
* Replaced `map_err` with `inspect_err` in various files to improve error logging without altering the error. (`dragonfly-client-backend/src/http.rs`, `dragonfly-client-backend/src/lib.rs`, `dragonfly-client-backend/src/object_storage.rs`, `dragonfly-client-storage/src/content.rs`) [[1]](diffhunk://#diff-f54c33c0ce074f6cd19d4a52f22bc25e5d0b9181fa00bddb3aaa9fb76b0276acL147-L152) [[2]](diffhunk://#diff-f54c33c0ce074f6cd19d4a52f22bc25e5d0b9181fa00bddb3aaa9fb76b0276acL193-L1 …
> feat: support transfer piece content from dfdaemon

- Cargo.lock
- Cargo.toml
> chore: update crate version to 0.2.1

- dragonfly-client-config/src/dfdaemon.rs
This pull request includes changes to improve the documentation and comments in the `dragonfly-client-config/src/dfdaemon.rs` file. The changes primarily focus on standardizing the capitalization and clarifying the descriptions within the comments.
Documentation improvements:
* Standardized capitalization in the workflow diagram comments to ensure consistency.
* Clarified the description of `cache_capacity` to better explain its purpose and usage, including a reference to the relevant API documentation.
> chore: optimize comments for storage cache

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/content.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
This pull request includes several changes to the `dragonfly-client` and `dragonfly-client-storage` modules. The most important changes involve updating dependencies, removing unused methods, and modifying metadata handling.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L33-R33): Updated `dragonfly-api` dependency version from `2.1.12` to `2.1.16`.
Removal of unused methods:
* [`dragonfly-client-storage/src/content.rs`](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL208-L227): Removed the `read_task_by_range` method from the `Content` implementation.
* [`dragonfly-client-storage/src/lib.rs`](diffhunk://#diff-09bca31ba146d9bc116819606a37c3f4073946a1e2af40382b3c41e440869e6eL73-L82): …
> feat: update ttl, persistent and piece_length when download persistent cache task started

- Cargo.lock
- Cargo.toml
This pull request includes updates to the `Cargo.toml` file, specifically updating the version numbers of various dependencies and the overall package version.
* Updated the package version from `0.2.6` to `0.2.7` in the `[workspace.package]` section.
* Updated the version of multiple dependencies from `0.2.6` to `0.2.7` in the `[workspace.dependencies]` section.
> chore: update cargo version to 0.2.7

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/resource/task.rs
This pull request includes several updates and improvements to the `dragonfly-client` project, including version updates and logging enhancements. The most important changes are summarized below:
Version updates in `Cargo.toml`:
* Updated the version of the `dragonfly-client` package and its dependencies from `0.2.7` to `0.2.8`. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31)
Logging enhancements:
* Added logging statements to the `has_enough_space` method in `dragonfly-client-storage/src/content.rs` to provide more detailed information about available space and content length.
Bug fix and code improvement:
* Corrected a comment and improved the …
> fix: if disk has no enough space, client return failed

- ci/Dockerfile
This pull request includes a small change to the `ci/Dockerfile` to enhance the set of installed utilities.
* [`ci/Dockerfile`](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL58-R58): Added `iotop` to the list of installed packages to improve monitoring capabilities.
> chore(ci/Dockerfile): add iotop for client image

- Cargo.lock
- Cargo.toml
This pull request includes version updates for the Dragonfly client packages in the `Cargo.toml` file. The most important changes include updating the version of the main package and its dependencies.
* Updated the version of the main package from `0.2.11` to `0.2.12` in the `[workspace.package]` section.
* Updated the versions of the dependencies from `0.2.11` to `0.2.12` in the `[workspace.dependencies]` section.
> chore: update cargo version to 0.2.12

- dragonfly-client-storage/src/content.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/header.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/task.rs
This pull request includes several changes to the `dragonfly-client` to enhance the header handling functionality and improve test coverage. The most important changes include adding a new header for output paths, implementing a function to retrieve this header, and adding comprehensive tests for various header retrieval functions.
Enhancements to header handling:
* [`dragonfly-client/src/proxy/header.rs`](diffhunk://#diff-1b7f22df92aaf0d22154da5c70908b559ad89e77f9d2e806bf1aa26281c84bccR54-R59): Added the `DRAGONFLY_OUTPUT_PATH_HEADER` constant to define a new header for specifying the output path in HTTP requests.
* [`dragonfly-client/src/proxy/header.rs`](diffhunk://#diff-1b7f22df92aaf0d22154da5c70908b559ad89e77f9d2e806bf1aa26281c84bccR156-R281): Implemented the `get_output_path` …
> feat: add X-Dragonfly-Output-Path header for proxy

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/resource/task.rs
This pull request includes updates to the `Cargo.toml` file to bump the version of several dependencies, as well as minor code changes in the `dragonfly-client` project to remove an unnecessary mutation of a variable.
Dependency version updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15): Updated the version of `dragonfly-client` and its subcomponents from `0.2.13` to `0.2.14`. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R33)
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R33): Updated the version of `dragonfly-api` from `2.1.28` …
> feat: remove piece_length in Register process

- .github/workflows/docker.yml
- Cargo.toml
- ci/Dockerfile.debug
This pull request includes several significant changes to the build and deployment process, as well as updates to the development environment. The most important changes include adding a new job to push a debug image to the registry, updating the `Cargo.toml` file to enable debug mode for the development profile, and creating a new Dockerfile for building the debug image.
Improvements to build and deployment process:
* [`.github/workflows/docker.yml`](diffhunk://#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94R106-R200): Added a new job `push_client_debug_image_to_registry` to build and push a debug image to the Docker and GitHub Container registries. This job includes steps for checking out the code, setting up QEMU and Docker Buildx, caching Docker layers, logging …
> chore(workflows/docker.yml): build debug image for client

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client/src/proxy/mod.rs
This pull request includes several changes to the `dragonfly-client` and `dragonfly-client-config` modules to improve buffer sizes and simplify the proxy code. The most important changes include increasing buffer sizes, adding a `Context` struct to simplify parameter passing, and using `BufWriter` for more efficient writing.
Buffer size improvements:
* [`dragonfly-client-config/src/dfdaemon.rs`](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddL191-R200): Increased the default buffer sizes for reading and writing pieces to disk and proxy read buffer size from 128KB and 32KB to 4MB. [[1]](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddL191-R200) [[2]](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815 …
> feat(dragonfly-client/proxy): improved data transfer efficiency in the proxy

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-init/src/bin/main.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/bin/dfstore/main.rs
- dragonfly-client/src/tracing/mod.rs
This pull request includes several changes to the `dragonfly-client` project, focusing on optimizing build profiles and removing the flamegraph tracing feature. The most important changes include updates to the `Cargo.toml` files and modifications to the tracing initialization logic.
Build profile optimizations:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L108-R111): Changed the release profile's `opt-level` from "z" to 3, set `lto` to "thin", and added `panic = "abort"` to improve performance.
Removal of flamegraph tracing feature:
* [`dragonfly-client-config/src/dfdaemon.rs`](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddL1388-L1390): Removed the `flamegraph` field from the `Tracing` struct.
* …
> feat: optimize profile.release and remove tracing-flame

- Cargo.lock
- Cargo.toml
- ci/Dockerfile
- ci/Dockerfile.debug
- dragonfly-client-util/Cargo.toml
- dragonfly-client-util/src/tls/mod.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/proxy/mod.rs
This pull request includes various changes to the `ci/Dockerfile`, `ci/Dockerfile.debug`, and several Rust files to enhance functionality and improve performance. The most important changes include adding dependencies, caching certificates, and updating Dockerfiles.
Dependency Additions:
* Added `lazy_static` and `lru` dependencies to `Cargo.toml` files. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R106) [[2]](diffhunk://#diff-1c96c45400d8ecf785eb0acb8bced3fbd8838ce5882e449bb66aceaf5497021dR32-R33) [[3]](diffhunk://#diff-651fbc571d827abadd8e14ed21f83bc11941b8733f2d9704b93ae13b4dbfbb31L68-R69)
Dockerfile Updates:
* Added installation of `zenith` from a GitHub repository in `ci/Dockerfile` and `ci/Dockerfile.debug`. …
> feat: add certs cache for generating self-signed certs

- dragonfly-client/src/proxy/mod.rs
This pull request includes changes to the `dragonfly-client/src/proxy/mod.rs` file to improve the handling of supported HTTP protocols by using a `lazy_static` variable. The most important changes are summarized below:
* Added `lazy_static` to the list of imports to facilitate the creation of static variables.
* Defined a `lazy_static!` block to create a static vector `SUPPORTED_HTTP_PROTOCOLS` containing the supported HTTP protocols (`http/1.1` and `http/1.0`).
* Replaced the inline definition of `alpn_protocols` in the `upgraded_tunnel` function with the `SUPPORTED_HTTP_PROTOCOLS` variable for better maintainability.
> feat: add static SUPPORTED_HTTP_PROTOCOLS for proxy

- dragonfly-client/src/resource/piece.rs
This pull request includes several changes to the `dragonfly-client/src/resource/piece.rs` file, primarily focusing on refactoring the rate limiter acquisition logic and improving the handling of content reading. The most important changes include moving the rate limiter acquisition logic to a different part of the method and replacing the usage of `content.as_slice()` with a `Cursor` for content reading.
* Moved the rate limiter acquisition logic from the beginning to the middle of the method in the `Piece` implementation to ensure it is only executed when necessary. [[1]](diffhunk://#diff-475bfaadbebd4a013fc563ecdf5dc59fc9f5258738fc46ff30b0ac3cea0ad515L476-L483) [[2]](diffhunk://#diff-475bfaadbebd4a013fc563ecdf5dc59fc9f5258738fc46ff30b0ac3cea0ad515R489-R496) …
> feat(dragonfly-client): optimize piece download performance

- ci/Dockerfile
- ci/Dockerfile.debug
- ci/Dockerfile.dfinit
This pull request includes changes to multiple Dockerfiles to switch the base images to use public ECR (Elastic Container Registry) URLs. This change ensures that the images are pulled from a reliable and consistent source.
Changes to base images in Dockerfiles:
* [`ci/Dockerfile`](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL1-R1): Updated the base images for `rust`, `alpine`, `golang`, and `debian` to use public ECR URLs. [[1]](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL1-R1) [[2]](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL39-R39) [[3]](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL52-R56)
* …
> chore: change the registry origin from dockerhub to ecr

- dragonfly-client-storage/src/storage_engine/rocksdb.rs
Add comprehensive unit tests for RocksdbStorageEngine.
The tests cover all primary functionality of the storage engine:
- Basic CRUD operations (put, get, delete)
- Batch deletion
- Object existence checking
- Standard and prefix-based iteration
- Raw data iteration
- Error handling for unregistered column families
Special attention was given to testing the prefix iteration functionality, which required careful handling of RocksDB's fixed-length prefix extractor configuration (64 bytes).
https://github.com/dragonflyoss/client/issues/399
The tests specifically focus on proper handling of the RocksDB prefix iterator functionality, which is a crucial feature for efficient querying of data with common prefixes.
> test: add unit tests for RocksdbStorageEngine

- ci/Dockerfile
- ci/Dockerfile.debug
This pull request includes changes to the `ci/Dockerfile` and `ci/Dockerfile.debug` files to update dependencies and remove unnecessary installations. The most important changes include the removal of the `bottom` tool installation and the addition of `iostat` and `net-tools` packages.
Updates to dependencies:
* [`ci/Dockerfile`](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL37): Removed the installation of the `bottom` tool to streamline the build process.
* [`ci/Dockerfile`](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL59-L66): Added `iostat` and `net-tools` to the list of installed packages to enhance system monitoring capabilities.
* [`ci/Dockerfile.debug`](diffhunk://#diff-13f9c6664d42189b9dcb3443624a438ddd6ed0ca …
> chore(ci/Dockerfile): add tools for image

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-storage/src/cache/lru_cache.rs
- dragonfly-client-storage/src/cache/mod.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
This pull request includes several changes to the `dragonfly-client-config` and `dragonfly-client-storage` modules to improve the cache system and update the configuration. The most important changes include modifying the cache capacity and task capacity settings, updating the LRU cache implementation, and adding documentation comments for better code clarity.
* [`dragonfly-client-config/src/dfdaemon.rs`](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddL203-R207): Changed the default cache capacity from 10GiB to 128MiB and removed the task capacity setting. Updated the `Storage` struct to use `ByteSize` for cache capacity. [[1]](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddL203-R207) …
> refactor: optimize storage cache

- ci/Dockerfile
- ci/Dockerfile.debug
This pull request includes updates to the Dockerfiles to enhance the debugging and runtime capabilities of the application. The primary changes involve adding new utilities and tools to the Docker images.
Enhancements to Dockerfiles:
* [`ci/Dockerfile`](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL57-R58): Added `infiniband-diags` and `libibverbs-utils` to the list of installed packages to improve diagnostics and networking capabilities.
* [`ci/Dockerfile.debug`](diffhunk://#diff-13f9c6664d42189b9dcb3443624a438ddd6ed0cab1893f225226779346027944L61-R62): Included `infiniband-diags` and `libibverbs-utils` in the list of installed packages to enhance debugging and performance monitoring.
> chore(ci/Dockerfile): add infiniband-diags and libibverbs-utils for container

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
This pull request includes several changes to the `dragonfly-client` project, focusing on updating dependencies and adding new functionalities. The most important changes are listed below:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L33-R33): Updated the `dragonfly-api` dependency version from `2.1.30` to `2.1.35`.
* [`dragonfly-client/src/grpc/dfdaemon_upload.rs`](diffhunk://#diff-ee96a329b9be744aa8bbeb4c7c8936c29ba529c4a4e51778ca7bfd31684c26a1L34-R38): Added new imports for `ExchangeIbVerbsQueuePairEndpointRequest`, `ExchangeIbVerbsQueuePairEndpointResponse`, and `IbVerbsQueuePairEndpoint` in the `use dragonfly_api::dfdaemon::v2` section.
* [`dragonfly-client/src/grpc/dfdaemon_upload.rs`](diffhunk://#diff-ee96a329b9be744aa8bbeb4c7c893 …
> feat(dragonfly-client/src/grpc): support exchange_ib_verbs_queue_pair_endpoint api

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/grpc/mod.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/piece_downloader.rs
This pull request includes significant updates to the `dragonfly-client` module, focusing on improving the downloader component and optimizing the gRPC connection settings. The most important changes include modifying the timeout settings for GRPC connections, replacing the `downloader_factory` with a more efficient `downloader` implementation, and adding new mechanisms for managing downloader clients.
Changes to timeout settings:
* [`dragonfly-client/src/grpc/mod.rs`](diffhunk://#diff-d859a94a5da0dde503031572af96e4c4e81cf8b4d702db0b332d8d4bf6153356L35-R35): Reduced the `CONNECT_TIMEOUT` for GRPC connections from 3 seconds to 2 seconds.
Enhancements to the downloader component:
* [`dragonfly-client/src/resource/piece.rs`](diffhunk://#diff-475bfaadbebd4a013fc563ecdf5dc59fc9f5258738fc46ff30b …
> feat(dragonfly-client/src/resource): reuse grpc client in piece downloader

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/content.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/header.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
- dragonfly-client/src/resource/task.rs
Refer to https://github.com/dragonflyoss/design/blob/main/systems-analysis/file-download-workflow-with-hard-link/README.md
This pull request includes several changes to the `dragonfly-client-storage` library, focusing on refactoring methods for handling tasks and persistent cache tasks, as well as adding instrumentation for better tracing. The most important changes include updating dependencies, refactoring task handling methods, and adding tracing instrumentation.
* Updated the version of `dragonfly-api` from `2.1.35` to `2.1.36` in `Cargo.toml`.
Refactoring task handling methods:
* Refactored methods in `dragonfly-client-storage/src/content.rs` to separate concerns and improve readability, including splitting `hard_link_or_copy_task` into `hard_link_task` and …
> feat: optimize hard link and copy logic

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/resource/piece.rs
This pull request includes updates to the version numbers in the `Cargo.toml` file to reflect the latest changes in the Dragonfly client packages.
* Updated `version` from "0.2.22" to "0.2.23" in the `[workspace.package]` section of `Cargo.toml`.
* Updated the versions of the Dragonfly client dependencies from "0.2.22" to "0.2.23" in the `[workspace.dependencies]` section of `Cargo.toml`.
> chore: update verison to 0.2.23

- dragonfly-client/src/resource/persistent_cache_task.rs
opt the code for best practice.
> chore: opt code under persistent_cache_task

- dragonfly-client/src/shutdown.rs
> test: add ut for shutdown

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/Cargo.toml
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/announcer/mod.rs
- dragonfly-client/src/gc/mod.rs
This pull request includes updates to version dependencies, optimizations for parallel processing, and improvements to logging for garbage collection operations. The most important changes are grouped below by theme.
* Updated the version of the workspace package in `Cargo.toml` from `0.2.23` to `0.2.24` and updated all related dependencies to match the new version. (`Cargo.toml`, [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31)
* Removed the `rayon` dependency from `dragonfly-client-storage/Cargo.toml` since parallel iteration was replaced with standard iteration.
* Replaced `.par_iter()` with `.iter()` in multiple methods in …
> fix: solve the memory leak caused by rayon

- dragonfly-client/src/resource/task.rs
> test: add ut for resource.task

- dragonfly-client-util/src/digest/mod.rs
> chroe: fix typo in ut

- dragonfly-client-util/src/digest/mod.rs
This pull request improves error handling and code readability in the `calculate_file_digest` function and updates imports for better organization in `dragonfly-client-util/src/digest/mod.rs`. The key changes include adding retry logic for interrupted read operations, enhancing logging, and simplifying the use of the `io` module.
* Enhanced the `calculate_file_digest` function to handle `io::ErrorKind::Interrupted` by retrying the read operation and logging a warning message using the `warn` macro.
* Updated the `use` statements to consolidate `std::io` imports into a single line and added the `warn` macro from the `tracing` crate.
* Replaced fully qualified `std::io` references with the shorter `io` alias throughout the `calculate_file_digest` function.
> feat: handle Interrupted error for io

- dragonfly-client-init/src/container_runtime/mod.rs
> comments(container_runtime): remove unused containerd config override

- .github/workflows/stale.yml
> chore(.github/workflows): change rules of the stale actions

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/resource/piece.rs
This pull request includes version updates in `Cargo.toml` and enhancements to span logging in `dragonfly-client/src/resource/piece.rs`. The most significant changes are the version bumps for dependencies and the addition of `piece_length` logging to improve traceability.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15): Updated the version of the workspace package and its dependencies from `0.2.32` to `0.2.33`. This ensures compatibility and includes potential bug fixes or improvements in the dependencies. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31)
* …
> feat: add piece_length for download piece span

- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
This pull request enhances telemetry and logging in the `dragonfly-client` by adding more detailed fields to spans for better observability. It modifies both `DfdaemonDownloadServerHandler` and `DfdaemonUploadServerHandler` implementations to include additional metadata such as `url`, `content_length`, and `piece_length`.
* Enhanced the `download_task` span to include `url` and `content_length` fields for better traceability of download requests. (`dragonfly-client/src/grpc/dfdaemon_download.rs`, [[1]](diffhunk://#diff-303fb9e5802b43f6e4657a81ed3ea511a911a64d8bf32abb0d1bea5cc127498dL225-R225) [[2]](diffhunk://#diff-303fb9e5802b43f6e4657a81ed3ea511a911a64d8bf32abb0d1bea5cc127498dR276)
* Added `content_length` to spans during content length validation and logging, improving diagnostics for …
> feat: add url, content_length and piece_length for tracing span

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/metrics/mod.rs
This pull request simplifies the `dragonfly-client/src/metrics/mod.rs` file by removing unused metrics and refactoring code related to system information handling. The changes primarily focus on eliminating redundant disk metrics and the associated system dependencies, resulting in a cleaner and more efficient implementation.
* Removed `DISK_WRITTEN_BYTES` and `DISK_READ_BYTES` metrics from the `lazy_static!` block, as they are no longer required.
* Updated `register_custom_metrics` and `reset_custom_metrics` functions to exclude the registration and resetting of the removed metrics. [[1]](diffhunk://#diff-2bed13877d63556b6f5d2e6bbe266693bd6e448b818486df45c9539e173f0888L378-L385) [[2]](diffhunk://#diff-2bed13877d63556b6f5d2e6bbe266693bd6e448b818486df45c9539e173f0888L416-L417)
* Removed …
> feat: remove DISK_WRITTEN_BYTES and DISK_READ_BYTES metrics

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/grpc/dfdaemon_upload.rs
This pull request includes updates to version numbers in `Cargo.toml`, logging enhancements, and optimizations in memory handling for piece uploads. The most important changes focus on improving maintainability and performance.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15): Updated the package version from `0.2.40` to `0.2.41` and adjusted dependency versions accordingly. This ensures compatibility and reflects the latest iteration of the project. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31)
* [`dragonfly-client-storage/src/content.rs`](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc …
> feat: bump version to 0.2.41 and optimize vector initialization in dfdaemon_upload

- dragonfly-client/src/grpc/dfdaemon_download.rs
This pull request introduces enhancements to the `DfdaemonDownloadServer` and its handler in the `dragonfly-client` project. The changes focus on improving configuration management, logging, timeout handling, and response construction for the `list_task_entries` method.
* Added a `config` field to `DfdaemonDownloadServerHandler` to manage configuration settings, and updated the server initialization to clone this configuration. (`dragonfly-client/src/grpc/dfdaemon_download.rs`, [[1]](diffhunk://#diff-303fb9e5802b43f6e4657a81ed3ea511a911a64d8bf32abb0d1bea5cc127498dR122) [[2]](diffhunk://#diff-303fb9e5802b43f6e4657a81ed3ea511a911a64d8bf32abb0d1bea5cc127498dR213-R215)
* Updated the `list_task_entries` method to include `task_id` and `url` in the tracing span for better observability. …
> refactor: list_task_entries in DfdaemonDownloadServerHandler

- dragonfly-client/src/grpc/dfdaemon_upload.rs
This pull request refactors the `DfdaemonUploadServer` and its handler in `dragonfly-client/src/grpc/dfdaemon_upload.rs` to improve error handling and make the code more robust. The key changes include modifying the `interface` field to be optional, refining how interface-related logic is handled, and removing unused imports.
* Changed the `interface` field in `DfdaemonUploadServerHandler` from `Interface` to `Option<Interface>` to handle cases where the interface may not be available.
* Updated the `DfdaemonUpload` implementation to check for the presence of the `interface` before accessing its properties, preventing potential runtime errors. [[1]](diffhunk://#diff-ee96a329b9be744aa8bbeb4c7c8936c29ba529c4a4e51778ca7bfd31684c26a1R1018-R1020) …
> feat(dragonfly-client): change interface optional in DfdaemonUploadServerHandler

- Cargo.lock
- Cargo.toml
This pull request updates the version of the Dragonfly client and its related dependencies in the `Cargo.toml` file to ensure consistency and reflect the latest changes.
* Updated the `version` field in the `[workspace.package]` section from `1.0.5` to `1.0.6`. (`Cargo.toml`, [Cargo.tomlL15-R15](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15))
* Updated the version of all Dragonfly client dependencies (`dragonfly-client`, `dragonfly-client-core`, `dragonfly-client-config`, `dragonfly-client-storage`, `dragonfly-client-backend`, `dragonfly-client-util`, `dragonfly-client-init`) from `1.0.5` to `1.0.6` in the `[workspace.dependencies]` section. (`Cargo.toml`, [Cargo.tomlL25-R31](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96 …
> chore: update crate version to 1.0.6

- dragonfly-client/src/proxy/header.rs
- dragonfly-client/src/proxy/mod.rs
This pull request introduces changes to enhance the handling of response headers in the `dragonfly-client` by adding support for a new task ID header and updating relevant functions to incorporate this header. The changes primarily focus on improving the clarity and functionality of the response headers.
* **Added a new response header constant**: Introduced `DRAGONFLY_TASK_ID_HEADER` to represent the task ID in response headers, along with documentation explaining its purpose. (`dragonfly-client/src/proxy/header.rs`, [dragonfly-client/src/proxy/header.rsL82-R90](diffhunk://#diff-1b7f22df92aaf0d22154da5c70908b559ad89e77f9d2e806bf1aa26281c84bccL82-R90))
* **Updated `make_response_headers` function**: Modified the function to accept a `task_id` parameter and include the …
> feat: add task ID response header in Dragonfly client proxy

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client/src/announcer/mod.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
This pull request simplifies the codebase by removing functionality related to seed peer cluster management and the `ManagerAnnouncer` component. The changes streamline the configuration and announcement logic by focusing on the scheduler while eliminating unused fields, functions, and dependencies.
* Removed the `cluster_id` and `keepalive_interval` fields from the `SeedPeer` struct in `dragonfly-client-config/src/dfdaemon.rs`, along with their associated default values and validation logic. [[1]](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddL229-L240) [[2]](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddL927-L938) [[3]](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddL947-L948) …
> refactor: remove the seed peer announcement to manager

- dragonfly-client-backend/src/http.rs
- dragonfly-client/src/proxy/header.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/task.rs
This pull request enhances error handling and reporting throughout the `dragonfly-client` project, focusing on more explicit error typing and improved communication of error sources to clients via HTTP response headers. The main changes include introducing a new error type system, updating error responses to include error source information, and refactoring code to utilize these new mechanisms.
**Error Type System and Header Reporting:**
* Added a new `ErrorType` enum in `dragonfly-client/src/proxy/header.rs` to represent the source of errors (`Backend`, `Proxy`, `Dfdaemon`), along with a corresponding HTTP header `X-Dragonfly-Error-Type` for error responses. This helps clients identify where an error originated.
* Refactored the `make_error_response` function in …
> feat: add the X-Dragonfly-Error-Type header to the response

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/resource/piece_downloader.rs
This pull request refactors the client management logic in `piece_downloader.rs` to streamline how client entries are retrieved and used, and adjusts the idle timeout and logging for client cleanup. The main changes focus on simplifying client entry access, improving code clarity, and making idle client cleanup more visible.
**Client management and code simplification:**
* Renamed the `client` method to `client_entry` and updated its return type to return the full `DfdaemonUploadClientEntry` instead of just the client, consolidating client retrieval logic and removing the now-unnecessary `get_client_entry` method. [[1]](diffhunk://#diff-53eaf4b7e9d819d0105f0f0a5c6af8421891328cb381e5c0502f3a5afb47e9c4L162-R169) [[2]](diffhunk://#diff-53eaf4b7e9d819d0105f0f0a5c6af8421891328cb381e5c0502f3a5af …
> refactor(downloader): rename client method and increase timeout

- Cargo.lock
- Cargo.toml
update dragonfly-client dependencies to 1.0.15
> build(deps): update dragonfly-client dependencies to 1.0.15

- Cargo.lock
- Cargo.toml
- dragonfly-client-backend/src/hdfs.rs
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/lib.rs
- dragonfly-client-backend/src/object_storage.rs
- dragonfly-client/src/bin/dfget/main.rs
This pull request updates several dependencies and refactors how HTTP clients and TLS providers are handled in the backend, particularly for object storage and HTTP modules. It also improves the way object storage operators are constructed, simplifies OSS credential handling, and adjusts test cases accordingly.
Dependency and compatibility updates:
* Updated multiple dependencies in `Cargo.toml`, including `dragonfly-client` packages to version `1.0.16`, downgraded `dragonfly-api` to `2.1.59`, updated `reqwest`, `hyper-rustls`, `rustls`, and replaced a git dependency on `opendal` with a crates.io version (`0.48.0`). TLS-related features and versions were also adjusted for compatibility. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) …
> chore(dependencies): update project dependencies and version

- dragonfly-client/src/bin/dfget/main.rs
> refactor(dfget): simplify argument parsing logic

- Cargo.lock
- Cargo.toml
- dragonfly-client-util/Cargo.toml
- dragonfly-client/Cargo.toml
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
This pull request introduces several dependency updates and a significant improvement to the initialization logic of the `DfdaemonDownloadClient` in the `dragonfly-client` crate. The main highlight is the addition of a new constructor that sets up the gRPC client with full TLS and connection configuration, supporting both secure and non-secure channels based on the provided configuration. Additionally, dependencies are streamlined to use workspace management for consistency across crates.
Dependency management improvements:
* Changed the `mocktail` dependency in `dragonfly-client-util` and `dragonfly-client` to use the workspace version, ensuring consistency and easier updates across the project. [[1]](diffhunk://#diff-1c96c45400d8ecf785eb0acb8bced3fbd8838ce5882e449bb66aceaf5497021dL54-R54 …
> fix(dfget): get wrong entries and add tests for entry retrieval functions
