- src/bin/dfdaemon/main.rs
- src/dynconfig/mod.rs
- src/lib.rs
Dynconfig will be periodically refreshed avaliable-schedulers and available_scheduler_cluster_id from manager.
> feat: refresh available_scheduler and available_scheduler_cluster_id

- Cargo.toml
- src/bin/dfdaemon/main.rs
- src/dynconfig/mod.rs
- src/grpc/manager.rs
- src/lib.rs
1. mut is like a virus in rust, the grpc channel is cloneable, and it's trival to clone the object, so we could clone the client to avoid mut ref
2. use anyhow context instead of unwrap the result
3. use anyhow::Error instead of Box<dyn Error>
> refactor: remove unnessery mut

- src/task/mod.rs
- src/task/piece.rs
- src/task/piece_collector.rs
> feat: rename argument remote_peer to parent

- src/config/dfdaemon.rs
- src/gc/mod.rs
- src/lib.rs
> feat: add gc configuration for dfdaemon

- dragonfly-client-init/src/container_runtime/containerd.rs
- dragonfly-client/src/proxy/mod.rs
> fix: add path to registry mirror and rename config name of containerd

- Cargo.lock
- dragonfly-client-storage/Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client-storage/src/storage_engine/mod.rs
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
Extract rocksdb logic into several traits like `StorageEngine`, `Transaction`, `Operation`, etc., so that `Metadata` is db-agnostic.
> feat: extract storage engine into traits

- rust-toolchain.toml
Change-Id: I6cd315ed953169cd5ecfc5f579fe6c2d24220e0f
ref: https://github.com/dragonflyoss/client/pull/401#issuecomment-2066990059
> chore: pin rust version to 1.77.2 to prevent rocksdb bug

- dragonfly-client/src/task/mod.rs
- dragonfly-client/src/task/piece.rs
> feat: optimize log of the interested pieces

- Cargo.lock
- dragonfly-client/Cargo.toml
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/stats/mod.rs
> feat: add heap profiling to dfdaemon

- Cargo.toml
- dragonfly-client/Dockerfile
> chore: add linux-perf to dfdaemon

- dragonfly-client-storage/src/content.rs
- dragonfly-client/src/proxy/mod.rs
> feat: change buffer size to 32KB

- Cargo.lock
- Cargo.toml
- dragonfly-client/Dockerfile
> chore: add pprof and graphviz for dfdameon container

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-storage/src/content.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/proxy/mod.rs
> feat: add buffer size config for dfdaemon

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
> feat: change concurrent number to 16

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/Cargo.toml
- dragonfly-client-storage/src/content.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-util/src/digest/mod.rs
> feat: calculate piece digest by blake3

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfcache.rs
- dragonfly-client-init/src/container_runtime/docker.rs
- dragonfly-client/src/announcer/mod.rs
- dragonfly-client/src/bin/dfcache/main.rs
- dragonfly-client/src/gc/mod.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/scheduler.rs
- dragonfly-client/src/task/mod.rs
> feat: add cache task api for grpc server

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/health.rs
- dragonfly-client/src/grpc/manager.rs
- dragonfly-client/src/grpc/scheduler.rs
- dragonfly-client/src/grpc/security.rs
> feat: change max_decoding_message_size and max_encoding_message_size to usize::MAX

- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/task/mod.rs
This pull request adds functionality to check task status and handle status data within the `dfdaemon_download` and `task` modules. The implementation includes new methods for deleting tasks and reclaiming local storage.
- https://github.com/dragonflyoss/Dragonfly2/issues/2818
The changes are required to improve the task management capabilities of the system. By adding these methods, users can better manage and delete tasks, ensuring efficient resource usage and task tracking.
- Design: https://www.yuque.com/baimo/fv9qk8/ed40b9sg7l9crdt4
- Design: https://github.com/dragonflyoss/Dragonfly2/issues/2818#issuecomment-2190419157
> feat: add delete task rpc implement by checking task status and reclaiming local storage with metadata.

- Cargo.lock
- dragonfly-client-backend/Cargo.toml
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/lib.rs
- dragonfly-client-backend/src/oss.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
This PR add support for Aliyun OSS protocol to download **ONE** file.
This PR is done by the following task:
Also, the `HeadRequest` now support list directory (recursively)
#496 
> feat: support OSS protocol to download single file

- Cargo.lock
- Cargo.toml
- dragonfly-client-backend/src/lib.rs
- dragonfly-client-backend/src/s3.rs
- dragonfly-client/src/bin/dfget/main.rs
The pull request adds AWS S3 Support for single file download in the `dragonfly-client-backend` trait through the use of [Apache OpenDAL](https://github.com/apache/opendal) which provides an interface to interact with the s3 storage system. 
https://github.com/dragonflyoss/client/issues/495
Currently, Dragonfly rust client does not support back-to-source downloading in AWS S3 protocol. Thus, this implementation based on `backend` trait aims to add such functionality to the system. 
Referenced projects:
- https://github.com/risingwavelabs/risingwave
- https://github.com/apache/opendal
> feat: S3 Support for Single File Download

- Cargo.lock
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/bin/dfget/main.rs
implement recursive download for dfget
This PR completes with the following tasks:
Other details will be shown in the code. 
#496 
> feat: implement recursive download for dfget

- Cargo.lock
- dragonfly-client-backend/Cargo.toml
- dragonfly-client-backend/src/object_storage.rs
- dragonfly-client/src/bin/dfget/main.rs
As title
This PR is done by the following task:
#496 
Solve the problem that download files with non-ascii name will return 404
> fix: fix url encode/decode bug

- Cargo.lock
- dragonfly-client/Cargo.toml
- dragonfly-client/src/announcer/mod.rs
1. According to [official migration guide](https://github.com/GuillaumeGomez/sysinfo/blob/master/migration_guide.md), migrate crate `sysinfo` from v0.29.6 to v0.30.13, in order to get more information.
2. Add missing `process_used_percent` field in announce host request.
3. Add missing `total` `free` `used` and `used_percent` for `Disk`, following [disk_usage()](https://github.com/rust-psutil/rust-psutil/blob/670454357ee89f5a74bad57da3f7105c5a7c9154/src/disk/sys/unix/disk_usage.rs#L42-L64).
> fix: add missing fields to the announce host request

- dragonfly-client-backend/src/http.rs
- dragonfly-client/src/grpc/mod.rs
Fix client received, frame: GoAway { error_code: ENHANCE_YOUR_CALM, last_stream_id: StreamId(1), debug_data: b"too_many_pings" }.
> fix: too_many_pings error for scheduler server

- Cargo.lock
- dragonfly-client-util/Cargo.toml
- dragonfly-client-util/src/digest/mod.rs
> feat: optimize calculate file by crc32

- Cargo.lock
- Cargo.toml
- dragonfly-client-backend/Cargo.toml
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/lib.rs
- dragonfly-client-backend/src/object_storage.rs
Add some basic unitest for oss in object storage
This PR is done by finishing the following tasks:
- `httpmock` does not support specify the port, but unitest need to.
More details are shown in the code
#496 
#399
> test: add unitest for oss

- Cargo.lock
- Cargo.toml
- dragonfly-client-backend/src/lib.rs
- dragonfly-client-backend/src/object_storage.rs
- dragonfly-client/src/bin/dfget/main.rs
Using `credential_path` instead of `credential` avoid users from inputting a long based-64 through command line. In addition, google recommends the use of ADC (https://cloud.google.com/docs/authentication#adc), and by not explicitly inputting a credential path, `opendal` would search and load the ADC internally. One thing to consider is that this may result in error handling issue. Lastly, since google storage url has the format of gs://bucket//path, a `gs` scheme for GCS is thus adopted.
> feat: Add GCS credential path and change GCS url scheme to gs

- Cargo.lock
- dragonfly-client-backend/Cargo.toml
- dragonfly-client-backend/src/lib.rs
Add unit test for dragonfly-client-backend/src/lib.rs, mainly for `BackendFactory`.
This PR is done by finishing the following tasks:
Other details are shown in the code. 
#496 
> test: add unit tests for `BackendFactory`

- dragonfly-client-backend/src/object_storage.rs
Add unit tests for object storage.
This PR is done by finishing the following tasks: 
#495 #496
> test: Add unit tests for object storage

- dragonfly-client-storage/src/content.rs
To ensure the parent directory are created at the destination path for recursive downloading. If this is not added, Azureblob recursive download would result in 
``` 
Bad Code: Internal error 
Message: No such file or directory (os error 2)
```
> fix: Ensure the parent directory of the destination exists

- Cargo.lock
- dragonfly-client/Cargo.toml
- dragonfly-client/src/bin/dfget/main.rs
Add unit tests for util function in dfget.
This PR is done by finishing the following tasks:
#496 
> test: add unit test for dfget

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
This pull request includes several updates and improvements across multiple files in the `dragonfly-client` project. The changes range from version updates and dependency adjustments to code enhancements and new tests. The most important changes include updating the version numbers in `Cargo.toml`, adding a sleep delay to avoid stream abortion errors, and introducing new tests for the `Piece` struct.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15): Updated the version of `dragonfly-client` and its dependencies from `0.1.110` to `0.1.111`. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31)
* …
> feat: avoid the out stream is aborted in proxy and add calculate_interested test

- dragonfly-client/src/announcer/mod.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/gc/mod.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
Set the connection between proxy with client HTTP/1
This pull request ensures that the connection between the proxy and the client is set to HTTP/1. Most public services negotiate to HTTP/1 after protocol negotiation (ALPN). However, the current proxy setup establishes an HTTP/2 connection with clients (e.g., curl), which can lead to request transfer failures. Setting up HTTP/1 is enough for now, may be extension for HTTP/x in the future.
https://github.com/dragonflyoss/client/issues/771
> ensure proxy connection HTTP/1 to prevent possible failures

- .github/workflows/docker.yml
- ci/Dockerfile
This pull request updates the GitHub Actions workflow configuration for Docker, focusing on adjusting the conditions under which Docker images are pushed. The most important changes include adding a `pull_request` trigger for the workflow and modifying the `push` condition for Docker images.
Workflow configuration updates:
* [`.github/workflows/docker.yml`](diffhunk://#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94R4-R5): Added a `pull_request` trigger for the workflow to run on pull requests to the `main` branch.
Docker image push condition adjustments:
* [`.github/workflows/docker.yml`](diffhunk://#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94L83-R86): Changed the `push` condition for Docker images to `false` and commented out the previous …
> feat(ops): Update Docker workflow for PRs on main branch

- dragonfly-client-config/src/dfdaemon.rs
This pull request includes changes to the `dragonfly-client-config` to add a new function for containerd query parameters and integrate it with the existing default proxy rule query parameters.
* [`dragonfly-client-config/src/dfdaemon.rs`](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddR287-R292): Added a new function `containerd_filtered_query_params` to handle filtered query parameters specific to containerd.
* [`dragonfly-client-config/src/dfdaemon.rs`](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddR317-R320): Integrated `containerd_filtered_query_params` into the `default_proxy_rule_filtered_query_params` function to include containerd-specific parameters in the task ID generation.
> feat: add query params of the containerd

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
This pull request includes updates to dependencies and modifications to the `PersistentCacheTask` struct in the `dragonfly-client` project. The most important changes include updating the version of the `dragonfly-api` dependency and modifying the fields in the `PersistentCacheTask` struct to reflect the current state of replicas.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L33-R33): Updated the `dragonfly-api` dependency from version `2.0.168` to `2.0.169` to ensure compatibility with the latest API changes.
Struct modifications:
* [`dragonfly-client/src/resource/persistent_cache_task.rs`](diffhunk://#diff-f95fb90718c7b67c4be3b2561b7ef633f021db56a99b04eb237aa1dac285ebf8L211-R212): Updated the `PersistentCacheTask` …
> feat: response current replica count for persistent cache task

- dragonfly-client-storage/src/metadata.rs
- dragonfly-client-util/src/http/mod.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/header.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/task.rs
This pull request involves several refactors and improvements across multiple files, primarily focusing on renaming functions and improving the efficiency of certain operations. The key changes include renaming functions for better clarity, removing redundant methods, and optimizing the conversion of header maps.
* Renamed `reqwest_headermap_to_hashmap` to `headermap_to_hashmap` and updated all references accordingly (`dragonfly-client-storage/src/metadata.rs`, `dragonfly-client-util/src/http/mod.rs`, `dragonfly-client/src/grpc/dfdaemon_download.rs`, `dragonfly-client/src/grpc/dfdaemon_upload.rs`, `dragonfly-client/src/proxy/mod.rs`). [[1]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L20-R20) [[2]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e …
> feat: optimize convert headermap to hashmap

- dragonfly-client/src/grpc/dfdaemon_download.rs
> feat: remove zstd comperssion in dfdaemon_download server

- dragonfly-client-backend/src/hdfs.rs
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/lib.rs
- dragonfly-client/src/bin/dfget/main.rs
> refactor: support hdfs for backend

- dragonfly-client-init/src/container_runtime/containerd.rs
> add ut for containerd init

- Cargo.lock
- Cargo.toml
- dragonfly-client-init/Cargo.toml
- dragonfly-client-init/src/container_runtime/docker.rs
- dragonfly-client/Cargo.toml
test dfinit yaml:
```yaml
proxy:
addr: http://0.0.0.0:4001   # address of client
containerRuntime:
docker:
configPath: '/etc/docker/daemon.json'
```
docker config after execution:
```json
{
"insecure-registries": [
"registry-internal.xxx.com"
],
"live-restore": true,
"proxies": {
"http-proxy": "http://0.0.0.0:4001",
"https-proxy": "http://0.0.0.0:4001"
}
```
pull image(log of dfdaemon):
> support docker runtime in dfinit with ut

- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
1. remove the access right of dfdaemon on socket's parent dir. (like ```chown -R root:root  /var/run/dragonfly/```).
2. start dfdaemon.
3. stuck, not able to response for any SIGNAL.
1. dfdaemon_download_grpc exit  before grpc_server_started_barrier.wait()  (no permission to create socket).
2. proxy.run() will never reach and wait for the missing barrier above.
3. shutdown_complete_tx.clone() for proxy will not be released inside the tokio thread.
4. the missing shutdown_complete_tx above leads to stuck at shutdown_complete_rx.recv().await.
5. game over.
always listen to shutdown and barrier at the same time.
> fix barrier synchronization on components exit for dfdaemon

- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
This pull request includes several improvements to the gRPC server implementations in the `dragonfly-client` project. The changes focus on enhancing the shutdown process and updating log messages for better clarity.
Enhancements to gRPC server implementations:
* [`dragonfly-client/src/grpc/dfdaemon_download.rs`](diffhunk://#diff-303fb9e5802b43f6e4657a81ed3ea511a911a64d8bf32abb0d1bea5cc127498dR143-R157): Added comments to explain the behavior when the gRPC server starts and waits for a shutdown signal, and updated log messages for consistency.
* [`dragonfly-client/src/grpc/dfdaemon_upload.rs`](diffhunk://#diff-ee96a329b9be744aa8bbeb4c7c8936c29ba529c4a4e51778ca7bfd31684c26a1R144-R160): Added comments to clarify the server startup and shutdown process, and corrected log messages to …
> feat: optimize logs for server started

- Cargo.lock
- Cargo.toml
- dragonfly-client-backend/src/http.rs
- dragonfly-client-backend/src/object_storage.rs
- dragonfly-client-config/src/dfdaemon.rs
This pull request includes several changes to improve the compression capabilities and default settings of the Dragonfly client. The most important changes include adding support for various compression algorithms in the `reqwest` client and updating the default download piece timeout.
Enhancements to compression capabilities:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L34-R34): Added `gzip`, `brotli`, `zstd`, and `deflate` features to the `reqwest` dependency.
* [`dragonfly-client-backend/src/http.rs`](diffhunk://#diff-f54c33c0ce074f6cd19d4a52f22bc25e5d0b9181fa00bddb3aaa9fb76b0276acR55-R58): Enabled `gzip`, `brotli`, `zstd`, and `deflate` support in the `reqwest::Client` builder. …
> feat: add gzip, deflate, brotli, zstd compressed for reqwest

- dragonfly-client-init/src/container_runtime/containerd.rs
Fix dfinit issue when updating registry config when multiple paths are present in config_path.
Sometimes `config_path` have multiple paths separated by colon e.g
```
[plugins."io.containerd.grpc.v1.cri".registry]
config_path = "/etc/containerd/certs.d:/etc/docker/certs.d"
```
In this case dfinit is creating folder at path ```/etc/containerd/certs.d\:/etc/docker/certs.d/```. It can be fixed by picking up the first path if multiple paths are added.
> Fix dfinit issue when containerd config_path have multiple paths

- dragonfly-client-core/src/error/errors.rs
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/piece_collector.rs
- dragonfly-client/src/resource/task.rs
This pull request primarily involves renaming various functions, structs, and comments to replace references to "remote peer" with "parent" in the `dragonfly-client` project. The changes span multiple files and affect error handling, documentation, and function names to ensure consistency with the new terminology.
* [`dragonfly-client-core/src/error/errors.rs`](diffhunk://#diff-5e06c855f1badd99103531909125c85aa23b8e19c1fba34a112dc0a0e6bc47e5L174-R177): Renamed `DownloadFromRemotePeerFailed` struct to `DownloadFromParentFailed` and updated associated error messages.
* [`dragonfly-client-core/src/error/mod.rs`](diffhunk://#diff-30b34d1fd4f012f66569fffc95749e5627c7a8bb3720dbcea2fa6659a7a5f85bL24-R24): Updated references to `DownloadFromRemotePeerFailed` to `DownloadFromParentFailed` in error …
> feat: rename remote peer to parent

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client/src/resource/piece.rs
> feat: add protocol for storage server

- Cargo.toml
- dragonfly-client-init/src/bin/main.rs
- dragonfly-client/src/bin/dfcache/main.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/bin/dfstore/main.rs
- dragonfly-client/src/tracing/mod.rs
This pull request includes several changes to the `dragonfly-client` project, focusing on improving logging and updating dependencies. The most important changes include updating the `lru` crate version, adding a new logging statement, and modifying the tracing initialization logic.
* Updated the `lru` crate version to `0.12.5` in `Cargo.toml`.
* Added a new logging statement using `tracing::info` in `dragonfly-client/src/proxy/cache.rs`.
* Removed the `redirect_stderr` parameter from the `init_tracing` function in `dragonfly-client/src/tracing/mod.rs`.
* Changed the logic to redirect `stderr` to a file only if `verbose` is not enabled in `dragonfly-client/src/tracing/mod.rs`.
> feat: replace redirect_stderr with args.verbose

- dragonfly-client-storage/src/content.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/cache.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
This pull request introduces several changes to the `dragonfly-client-storage` and related modules to enhance the reading and caching mechanisms, as well as to improve the upload functionality. The most important changes include adding dual read functionality, refactoring existing read methods to use buffered readers, and updating the cache logic.
* [`dragonfly-client-storage/src/content.rs`](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL215-R229): Added `BufReader` to improve reading performance and introduced a new method `read_piece_with_dual_read` to support dual read functionality. [[1]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL215-R229) [[2]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bcc …
> feat: calculate piece range and store the actual piece reader

- dragonfly-client-storage/src/content.rs
- dragonfly-client/src/proxy/cache.rs
- dragonfly-client/src/proxy/mod.rs
This pull request includes several changes aimed at refactoring the code for calculating piece ranges and improving the test coverage. The main changes involve extracting the `calculate_piece_range` function into a standalone function and updating the related code to use this new function.
Refactoring and code improvement:
* [`dragonfly-client-storage/src/content.rs`](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdR255-L270): Extracted the logic for calculating the target offset and length based on the range into a new function `calculate_piece_range`. This function is now called in the `impl Content` block instead of the inline logic. [[1]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdR255-L270) …
> test: add unit tests for calculate_piece_range

- Cargo.lock
- Cargo.toml
This pull request includes version updates for the `dragonfly-client` and its dependencies in the `Cargo.toml` file. 
* Updated `version` from "0.1.125" to "0.1.126" in the `[workspace.package]` section.
* Updated the versions of `dragonfly-client` and its related dependencies from "0.1.125" to "0.1.126" in the `[workspace.dependencies]` section.
> chore: update cargo version to 0.1.126

- dragonfly-client/src/gc/mod.rs
This pull request includes updates to the garbage collection logic in the `dragonfly-client` project. The changes improve the handling of tasks based on their download status and content length.
Key updates to garbage collection logic:
* Enhanced logic to handle tasks with different download statuses, ensuring that tasks with finished downloads and valid content lengths have their space correctly evicted.
* Added conditions to skip tasks without content length unless the task has failed, in which case it logs the failure and assigns an evicted space of 0.
> fix: when the task has started and did not download the data, gc is failed

- Cargo.lock
- Cargo.toml
This pull request includes updates to the `Cargo.toml` file to increment the version numbers for the `dragonfly-client` and its dependencies from `0.1.126` to `0.1.127`.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15): Updated the version of `dragonfly-client` and its dependencies to `0.1.127`. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31)
> chore: update crate version to v0.1.127

- dragonfly-client-config/src/dfdaemon.rs
This pull request includes several updates and improvements to the `dfdaemon.rs` file in the `dragonfly-client-config` module. The changes primarily focus on refining the `ParentSelector` configuration and updating associated documentation.
* Added `default_parent_selector_sync_interval` and `default_parent_selector_capacity` functions to set default values for the sync interval and capacity of the parent selector.
* Removed redundant definitions of `default_parent_selector_sync_interval` and `default_parent_selector_capacity` to avoid duplication. [[1]](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddL137-L142) [[2]](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddL227-R233)
* Updated comments to clarify the functionality …
> chore: optimize comments of the ParentSelector config

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/Cargo.toml
- dragonfly-client-storage/src/content.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-util/Cargo.toml
- dragonfly-client-util/src/digest/mod.rs
This pull request includes several changes to the `dragonfly-client` project, focusing on version updates and the removal of CRC32 ISO 3309 support. The most important changes include updating the version numbers in `Cargo.toml`, removing dependencies and methods related to CRC32 ISO 3309, and simplifying the codebase by eliminating unnecessary checks.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15): Updated the version of `dragonfly-client` and its dependencies from `0.2.1` to `0.2.2`. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31)
* …
> feat: remove crc32 iso3309 from write piece func

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/content.rs
This pull request includes updates to the `Cargo.toml` file and improvements to the `dragonfly-client-storage` module. The most important changes include version updates for dependencies and the refactoring of content handling to use `tokio_util::io::InspectReader`.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15): Updated the version of the workspace package and dependencies from "0.2.3" to "0.2.4". [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31)
Content handling improvements:
* [`dragonfly-client-storage/src/content.rs`](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc …
> feat: use InspectReader to calculate crc32

- dragonfly-client-config/src/dfdaemon.rs
**Cache storage**: When a user triggers a preheat task request, the downloaded piece content will be stored in the cache. Subsequently, when other peers request downloading the same content, the preheated peer can upload the piece content directly from memory, bypassing disk I/O and reducing the overhead associated with disk reads.
```yaml
storage:
cache_capacity: 100
```
https://github.com/dragonflyoss/dragonfly/issues/3742
> feat: add cache configuration support for preheat tasks

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/resource/piece.rs
This pull request includes updates to the `Cargo.toml` file and enhancements to the rate limiter configuration in the `dragonfly-client` project. The most important changes include updating the version of the dependencies and adding a maximum limit to the rate limiter.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15): Updated the version of the package from `0.2.4` to `0.2.5`.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31): Updated the version of multiple dependencies from `0.2.4` to `0.2.5`.
Rate limiter enhancements:
* [`dragonfly-client/src/resource/piece.rs`](diffhunk://#diff-475bfaadbebd4a013fc563ecdf5dc59fc9f5258738fc46ff30b0ac3cea0ad515R106): Added …
> feat: add max for ratelimit

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
This pull request includes several significant changes to the `dragonfly-client` project, primarily focusing on refactoring and adding new functionalities related to persistent cache tasks. The most important changes include updating dependencies, modifying method signatures and implementations, and adding new methods to handle persistent cache pieces.
* Updated the version of `dragonfly-api` from `2.1.3` to `2.1.6` in `Cargo.toml`.
* Renamed and refactored the `create_persistent_persistent_cache_task` method to `create_persistent_cache_task` in `dragonfly-client-storage/src/lib.rs` and `dragonfly-client-storage/src/metadata.rs`. This change also involved removing the `digest` parameter and related logic. [[1]](diffhunk://#diff-09bca31ba146d9bc116819606a37c3f4073946a1e2af40382b3c41e440869e …
> feat: upload persistent cache task by piece level

- Cargo.lock
- Cargo.toml
- dragonfly-client-util/Cargo.toml
- dragonfly-client-util/src/id_generator/mod.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
This pull request includes several updates and improvements across multiple files in the `dragonfly-client` project. The most important changes include updating dependencies, switching the hashing algorithm, adding logging for better traceability, and modifying request handling to improve error reporting and timeout management.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L33-R33): Updated `dragonfly-api` version from `2.1.6` to `2.1.9`.
* [`dragonfly-client-util/Cargo.toml`](diffhunk://#diff-1c96c45400d8ecf785eb0acb8bced3fbd8838ce5882e449bb66aceaf5497021dL33-R33): Replaced `crc32fast` with `wyhash` version `0.5.0`.
Hashing algorithm switch:
* [`dragonfly-client-util/src/id_generator/mod.rs`](diffhunk://#diff-0facc381 …
> feat: generate persistent task id by wyhash

- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/main.rs
- dragonfly-client/src/bin/dfcache/remove.rs
- dragonfly-client/src/bin/dfcache/stat.rs
> feat: add args for dfcache

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-util/src/id_generator/mod.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/persistent_cache_task.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/piece_collector.rs
- dragonfly-client/src/resource/piece_downloader.rs
- dragonfly-client/src/resource/task.rs
This pull request includes several updates and improvements to the `dragonfly-client` project, focusing on enhancing the persistent cache functionality and improving error handling. The most important changes are summarized below:
* Added multiple new methods to the `Storage` implementation in `dragonfly-client-storage/src/lib.rs` to handle persistent cache pieces, including methods for starting, finishing, failing, uploading, and checking the existence of persistent cache pieces. [[1]](diffhunk://#diff-09bca31ba146d9bc116819606a37c3f4073946a1e2af40382b3c41e440869e6eR520-R657) [[2]](diffhunk://#diff-09bca31ba146d9bc116819606a37c3f4073946a1e2af40382b3c41e440869e6eR693-R731)
* Updated the `IDGenerator` implementation in `dragonfly-client-util/src/id_generator/mod.rs` to generate a more …
> feat: support download persistent cache task from parents

- dragonfly-client/src/resource/piece.rs
This pull request includes changes to the `RateLimiter` configuration in the `Piece` implementation within the `dragonfly-client` project. The primary change involves adjusting the maximum limit for rate limiting by incorporating the `MAX_PIECE_COUNT` constant.
Changes to rate limiting configuration:
* [`dragonfly-client/src/resource/piece.rs`](diffhunk://#diff-475bfaadbebd4a013fc563ecdf5dc59fc9f5258738fc46ff30b0ac3cea0ad515L106-R106): Updated the `max` parameter in the `RateLimiter` builder for download, upload, and proxy prefetch rate limits to use `(MAX_PIECE_LENGTH * MAX_PIECE_COUNT) as usize` instead of `MAX_PIECE_LENGTH as usize`. [[1]](diffhunk://#diff-475bfaadbebd4a013fc563ecdf5dc59fc9f5258738fc46ff30b0ac3cea0ad515L106-R106) …
> fix: the maximum download speed is less than 16M/s in v0.2.5 client

- dragonfly-client/src/resource/piece.rs
This pull request includes modifications to the rate limiter configuration in the `dragonfly-client/src/resource/piece.rs` file. The changes aim to make the rate limiter's maximum value configurable based on the provided configuration rather than using hardcoded constants.
Rate limiter configuration changes:
* Updated the download rate limiter to use `config.download.rate_limit` for the maximum value instead of hardcoded constants.
* Updated the upload rate limiter to use `config.upload.rate_limit` for the maximum value instead of hardcoded constants.
* Updated the proxy prefetch rate limiter to use `config.proxy.prefetch_rate_limit` for the maximum value instead of hardcoded constants.
> feat: set max of the RateLimiter to the rate limit in config

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
This pull request includes updates to the `Cargo.toml` file to increment the version numbers of several dependencies and the package itself. 
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15): Updated the package version from `0.2.8` to `0.2.9`.
* `Cargo.toml`: Updated the versions of the following dependencies from `0.2.8` to `0.2.9`:
- `dragonfly-client`
- `dragonfly-client-core`
- `dragonfly-client-config`
- `dragonfly-client-storage`
- `dragonfly-client-backend`
- `dragonfly-client-util`
- `dragonfly-client-init`
> feat: get absolute path for dfdaemon import file

- ci/Dockerfile
- dragonfly-client-storage/src/metadata.rs
This pull request includes changes to the `ci/Dockerfile` and the `dragonfly-client-storage/src/metadata.rs` file. The most important changes are the addition of a new package to the Dockerfile and the simplification of the expiration logic in the `PersistentCacheTask` implementation.
* [`ci/Dockerfile`](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL57-R57): Added `iperf3` to the list of packages installed during the Docker image build process. This addition ensures that `iperf3` is available in the Docker image for network performance testing.
* [`dragonfly-client-storage/src/metadata.rs`](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L188-R188): Simplified the expiration check in the `is_expired` method of the …
> feat: add iperf3 for Dockerfile and change is_expired for PersistentCacheTask

- .github/workflows/docker.yml
- Cargo.lock
- Cargo.toml
- ci/Dockerfile
This pull request includes several important updates to the build and versioning configuration files. The changes primarily focus on updating dependencies and improving the Docker build process.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15): Updated the version of various `dragonfly-client` components from `0.2.9` to `0.2.10`. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31)
* [`.github/workflows/docker.yml`](diffhunk://#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94L4-L8): Removed the `pull_request` trigger and its associated branch and path filters, leaving only …
> chore(ci/Dockerfile): add fio for client image

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/metadata.rs
- dragonfly-client-util/src/digest/mod.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/resource/piece_downloader.rs
This pull request includes several changes to improve the calculation and verification of piece metadata digests in the `dragonfly-client` project. The key changes involve updating the `calculate_digest` method, ensuring the integrity of piece metadata, and updating dependencies.
* [`dragonfly-client-storage/src/metadata.rs`](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L306-R318): Enhanced the `calculate_digest` method to include additional metadata fields and ensure the integrity of piece metadata.
* [`dragonfly-client/src/grpc/dfdaemon_upload.rs`](diffhunk://#diff-ee96a329b9be744aa8bbeb4c7c8936c29ba529c4a4e51778ca7bfd31684c26a1R885-R886): Added digest calculation and verification in the `DfdaemonUpload` implementation to ensure the integrity of piece …
> feat: calculate digest of the persistent cache piece to check the integrity of the metadata

- dragonfly-client/src/grpc/dfdaemon_download.rs
This pull request includes changes to the `dragonfly-client` to enhance the handling of Unix domain sockets and permissions.
Enhancements to Unix domain sockets and permissions:
* [`dragonfly-client/src/grpc/dfdaemon_download.rs`](diffhunk://#diff-303fb9e5802b43f6e4657a81ed3ea511a911a64d8bf32abb0d1bea5cc127498dR45): Added import for `PermissionsExt` from `std::os::unix::fs` to handle Unix file permissions.
* [`dragonfly-client/src/grpc/dfdaemon_download.rs`](diffhunk://#diff-303fb9e5802b43f6e4657a81ed3ea511a911a64d8bf32abb0d1bea5cc127498dL127-R137): Added code to set permissions for the Unix domain socket to `0o660` after binding it, ensuring proper access control.
https://github.com/dragonflyoss/dragonfly/issues/3811
> feat: set permissions for Unix Domain Socket in dfdaemon_download

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
This pull request introduces new rate limiting features for the download and upload gRPC servers in the `dragonfly-client-config` and makes associated updates to the `dragonfly-client` codebase. The most important changes include adding default rate limits, updating server structures to include these limits, and incorporating the `ServiceBuilder` to apply concurrency limits and load shedding.
* [`dragonfly-client-config/src/dfdaemon.rs`](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddR63-R68): Added functions `default_download_request_rate_limit` and `default_upload_request_rate_limit` to define default rate limits for download and upload requests. Updated `DownloadServer` and `UploadServer` structs to include `request_rate_limit` fields with default …
> feat: add concurrency limit for grpc server

- .github/workflows/docker.yml
This pull request includes the addition of a Trivy vulnerability scanner and the upload of scan results to the GitHub Security tab in the `.github/workflows/docker.yml` file. These changes enhance the security checks during the CI/CD pipeline.
Security enhancements:
* Added a step to run the Trivy vulnerability scanner in tarball mode, scanning for critical and high severity issues, and outputting the results in SARIF format. [[1]](diffhunk://#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94R88-R100) [[2]](diffhunk://#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94R183-R195)
* Added a step to upload the Trivy scan results to the GitHub Security tab using the `github/codeql-action/upload-sarif` action. …
> chore: add trivy action for vulnerability scanner

- .github/workflows/docker.yml
This pull request includes a change to the `docker.yml` workflow file to update the image reference used by the Trivy vulnerability scanner.
* [`.github/workflows/docker.yml`](diffhunk://#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94L91-R91): Updated the `image-ref` in the Trivy vulnerability scanner step from `dragonflyoss/${{ matrix.module }}` to `dragonflyoss/client`.
> chore: rename image-ref in Trivy vulnerability scanner actions

- .github/workflows/docker.yml
This pull request includes a change to the `.github/workflows/docker.yml` file to update the `image-ref` used in the Trivy vulnerability scanner step.
* [`.github/workflows/docker.yml`](diffhunk://#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94L186-R186): Changed the `image-ref` from `dragonflyoss/${{ matrix.module }}` to `dragonflyoss/dfinit` in the Trivy vulnerability scanner step.
> chore(workflows/docker): fix image-ref for dfinit in trivy scanner

- dragonfly-client-storage/src/content.rs
- dragonfly-client/src/proxy/cache.rs
- dragonfly-client/src/resource/piece.rs
This pull request includes several updates to test functions in the `dragonfly-client-storage` and `dragonfly-client` modules. The changes primarily involve renaming test functions for consistency and adding new tests.
Test function updates:
* [`dragonfly-client-storage/src/content.rs`](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL656-R656): Renamed `should_calculate_piece_range` to `test_calculate_piece_range` for consistency.
* [`dragonfly-client/src/proxy/cache.rs`](diffhunk://#diff-fe6d2a7cd174669b339e84d9662fd7b5e8af3ac35a7bc0a4e780f811d63dec95L155-R155): Renamed `should_calculate_piece_range` to `test_calculate_piece_range` for consistency.
* [`dragonfly-client/src/resource/piece.rs`](diffhunk://#diff-475bfaadbebd4a013fc563ecdf5dc59fc9f5258738fc46 …
> test(dragonfly-client-storage): add test case for has_enough_space

- Cargo.lock
- dragonfly-client-util/Cargo.toml
- dragonfly-client/src/bin/dfcache/import.rs
This pull request includes a small change to the `dragonfly-client-util/Cargo.toml` file. The change removes the `wyhash` dependency from the project.
> feat(dragonfly-client-util): remove wyhash package

- dragonfly-client/src/grpc/dfdaemon_download.rs
This pull request includes a change to the `DfdaemonDownloadServer` implementation in the `dragonfly-client` project to improve error handling when removing an old Unix domain socket file.
Error handling improvement:
* [`dragonfly-client/src/grpc/dfdaemon_download.rs`](diffhunk://#diff-303fb9e5802b43f6e4657a81ed3ea511a911a64d8bf32abb0d1bea5cc127498dL134-R138): Modified the code to handle errors gracefully when removing an old Unix domain socket file by using `unwrap_or_else` to log an informational message if the removal fails.
> feat: cleaning up Unix Domain Sockets to avoid crashes

- .github/workflows/release.yml
- dragonfly-client-storage/src/storage_engine/mod.rs
- dragonfly-client-storage/src/storage_engine/rocksdb.rs
- dragonfly-client/src/grpc/interceptor.rs
- rust-toolchain.toml
This pull request includes a small change to the `.github/workflows/release.yml` file. The change specifies the Rust toolchain version to be installed during the release workflow.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R156-R157): Added the `toolchain` parameter with the value `1.82.0` to the Rust installation step.
> chore(release): set toolchain to 1.82.0

- .github/workflows/docker.yml
This pull request includes a minor change to the `.github/workflows/docker.yml` file. The change updates the `image-ref` parameter for the Trivy vulnerability scanner to use a debug version of the image.
* [`.github/workflows/docker.yml`](diffhunk://#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94L186-R186): Updated `image-ref` parameter to `dragonflyoss/client:${{ steps.get_version.outputs.VERSION }}-debug` for the Trivy vulnerability scanner.
> chore(workflows/docker.yaml): add debug suffix for trivy

- dragonfly-client/src/proxy/mod.rs
This pull request includes several changes to the `async fn proxy_via_dfdaemon` function in the `dragonfly-client/src/proxy/mod.rs` file. The changes focus on improving the efficiency and correctness of the proxy function.
* Increased the buffer size for the `tokio::io::duplex` from 256 KB to 512 KB to enhance data throughput.
* Modified the loop to remove the `piece_reader` from `finished_piece_readers` when it is being processed, ensuring that each piece is only processed once.
* Removed redundant `finished_piece_readers.remove(&need_piece_number)` call since the reader is already removed within the loop condition.
> feat(dragonfly-client/proxy): eliminate potential memory leak in piece reader handling

- ci/Dockerfile.debug
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/grpc/mod.rs
- dragonfly-client/src/resource/piece_collector.rs
- dragonfly-client/src/resource/piece_downloader.rs
This pull request includes multiple changes to the `dragonfly-client` and `ci/Dockerfile.debug` to enhance functionality and improve performance. The most important changes are summarized below:
* Added a new parameter `is_download_piece` to the `DfdaemonUploadClient::new` method, allowing the client to use different timeouts based on the type of request. [[1]](diffhunk://#diff-ee96a329b9be744aa8bbeb4c7c8936c29ba529c4a4e51778ca7bfd31684c26a1L1447-R1451) [[2]](diffhunk://#diff-ee96a329b9be744aa8bbeb4c7c8936c29ba529c4a4e51778ca7bfd31684c26a1R1460-R1467) [[3]](diffhunk://#diff-ee96a329b9be744aa8bbeb4c7c8936c29ba529c4a4e51778ca7bfd31684c26a1L1468-R1480) [[4]](diffhunk://#diff-ee96a329b9be744aa8bbeb4c7c8936c29ba529c4a4e51778ca7bfd31684c26a1L1483-R1495)
* Increased the GRPC connection timeout …
> fix(dragonfly-client/resource/piece_collector.rs): remove download piece number

- .github/workflows/docker.yml
- ci/Dockerfile.debug
This pull request includes several changes to the Docker workflow and the debug Dockerfile. The most important changes involve updating cache paths in the workflow and adding a new tool to the debug Dockerfile.
* [`.github/workflows/docker.yml`](diffhunk://#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94L145-R145): Updated the cache path for Docker layers from `/tmp/.buildx-cache-debug` to `/tmp/.buildx-cache` to streamline caching.
* [`.github/workflows/docker.yml`](diffhunk://#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94L198-R199): Modified the cache move step to reflect the new cache path, ensuring the cache is correctly moved and cleaned up.
* [`ci/Dockerfile.debug`](diffhunk://#diff-13f9c6664d42189b9dcb3443624a438ddd6ed0cab1893f2252267793 …
> chore(ci/Dockerfile.debug): add flamegraph for debug image

- dragonfly-client-storage/src/content.rs
- dragonfly-client/src/proxy/mod.rs
This pull request includes several changes to the `dragonfly-client-storage` and `dragonfly-client` projects to improve the handling of I/O operations and ensure proper ordering of buffer initialization. The most important changes include reordering buffer initialization in the `Content` implementation and modifying the `proxy_via_dfdaemon` function to correctly initialize the status code writer.
Improvements to buffer initialization:
* [`dragonfly-client-storage/src/content.rs`](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL362-L371): Reordered the initialization of `BufWriter` to occur before the CRC32 calculation and piece copying in the `Content` implementation. [[1]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL3 …
> refactor(dragonfly-client-storage): optimize buffer creation sequence for better readability

- ci/Dockerfile
- ci/Dockerfile.debug
This pull request includes changes to the `ci/Dockerfile` and `ci/Dockerfile.debug` files to replace the `zenith` tool with the `bottom` tool. The changes ensure that the new tool is installed and copied to the appropriate locations in the Docker images.
Changes in `ci/Dockerfile`:
* Replaced the installation of `zenith` with `bottom` using the `cargo install` command.
* Updated the `COPY` command to copy the `btm` binary instead of the `zenith` binary.
Changes in `ci/Dockerfile.debug`:
* Replaced the installation of `zenith` with `bottom` using the `cargo install` command.
* Updated the `COPY` command to copy the `btm` binary instead of the `zenith` binary.
> chore(ci/Dockerfile): add bottom for client image

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/content.rs
- Bumped version from 0.2.18 to 0.2.19 across all packages
- Modified hard link logic in content.rs to:
- Move existence check after initial hard link attempt
- Handle AlreadyExists error case more gracefully
- Apply consistent behavior for both regular and persistent cache tasks
- Maintains original functionality while improving error handling flow
> fix(dragonfly-client-storage): improve hard link handling in content storage

- dragonfly-client-storage/src/cache/lru_cache.rs
- dragonfly-client-storage/src/cache/mod.rs
This pull request includes several changes to the `dragonfly-client-storage` crate, specifically focusing on the `lru_cache.rs` file. The changes aim to improve code documentation, simplify the implementation, and refactor the `LruCache` structure.
* Added Apache License 2.0 header to `lru_cache.rs` file.
* Added documentation comments for `KeyRef`, `KeyWrapper`, `Entry`, and `LruCache` structs and their methods. [[1]](diffhunk://#diff-7d8f8ec7e65a57ac5bd1ee29f70410b71e2be0be94491e27d25af24e7a086231R35) [[2]](diffhunk://#diff-7d8f8ec7e65a57ac5bd1ee29f70410b71e2be0be94491e27d25af24e7a086231R46-R68) [[3]](diffhunk://#diff-7d8f8ec7e65a57ac5bd1ee29f70410b71e2be0be94491e27d25af24e7a086231R77-R86) [[4]](diffhunk://#diff-7d8f8ec7e65a57ac5bd1ee29f70410b71e2be0be94491e27d25af24e7a086231R95-R105) …
> refactor(dragonfly-client-storage): optimize lru_cache for storage

- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/resource/piece_downloader.rs
This pull request includes several changes to the `dragonfly-client` codebase, primarily focusing on the `grpc` and `resource` modules. The most important changes involve removing the `tcp_nodelay` setting from the `DfdaemonUploadServer` and `DfdaemonUploadClient` implementations, updating the `client` method in `GRPCDownloader` to handle concurrent requests more effectively, and adding an `info` log level to the `piece_downloader` module.
Changes to `grpc` module:
* Removed `tcp_nodelay` setting from `DfdaemonUploadServer` and `DfdaemonUploadClient` implementations in `dfdaemon_upload.rs`. [[1]](diffhunk://#diff-ee96a329b9be744aa8bbeb4c7c8936c29ba529c4a4e51778ca7bfd31684c26a1L148) [[2]](diffhunk://#diff-ee96a329b9be744aa8bbeb4c7c8936c29ba529c4a4e51778ca7bfd31684c26a1L1487) …
> feat(dragonfly-client): reducing lock contention and improving concurrency

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-storage/src/cache/mod.rs
- dragonfly-client-storage/src/content.rs
This pull request introduces several changes to improve the `dragonfly-client` project, focusing on documentation formatting and enhancing the test coverage for the `content` module. The most important changes include updating documentation comments to specify the text format and adding comprehensive tests for various functionalities in the `content` module.
Documentation improvements:
* Updated documentation comments to specify the text format in `dragonfly-client-config/src/dfdaemon.rs` and `dragonfly-client-storage/src/cache/mod.rs`. [[1]](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddL608-R609) [[2]](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddL957-R959) [[3]](diffhunk://#diff-51f0ccb672e36dc2c15f60176ef4f9c63eae4b …
> test(dragonfly-client-storage): add unit tests for content and fix doctest syntax

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/proxy/mod.rs
This pull request introduces changes to the `dragonfly-client/src/proxy/mod.rs` file to handle the port number in HTTPS requests. The most important changes include adding the port number to various function parameters and updating the URI formatting to include the port.
Handling port number in HTTPS requests:
* [`dragonfly-client/src/proxy/mod.rs`](diffhunk://#diff-6421011d65f9faa2a693ea46e321cc00e07b77ef8792a1b795d1db98d9e5ec4cR433): Added a default port number (443) to the `https_handler` function.
* [`dragonfly-client/src/proxy/mod.rs`](diffhunk://#diff-6421011d65f9faa2a693ea46e321cc00e07b77ef8792a1b795d1db98d9e5ec4cR472): Included the port number in the parameters for the `upgraded_tunnel` function.
* [`dragonfly-client/src/proxy/mod.rs`](diffhunk://#diff-6421011d65f9faa2a693ea46e321c …
> feat(dragonfly-client/src/proxy): add port parameter to HTTPS proxy handler

- dragonfly-client/src/proxy/header.rs
- dragonfly-client/src/proxy/mod.rs
This pull request to the `dragonfly-client` project includes changes to add support for the "force hard link" feature in HTTP requests. The most important changes include the addition of a new header constant, a function to retrieve the header value, and modifications to the download task request to utilize this new feature.
* [`dragonfly-client/src/proxy/header.rs`](diffhunk://#diff-1b7f22df92aaf0d22154da5c70908b559ad89e77f9d2e806bf1aa26281c84bccR63-R68): Added a new constant `DRAGONFLY_FORCE_HARD_LINK_HEADER` for the "X-Dragonfly-Force-Hard-Link" header. This header indicates whether the downloaded file must be hard linked to the output path.
* [`dragonfly-client/src/proxy/header.rs`](diffhunk://#diff-1b7f22df92aaf0d22154da5c70908b559ad89e77f9d2e806bf1aa26281c84bccR181-R195): Introduced …
> feat(dragonfly-client/src/proxy): add X-Dragonfly-Force-Hard-Link header for proxy

- dragonfly-client-storage/benches/cache.rs
- dragonfly-client-storage/benches/lru_cache.rs
- dragonfly-client-storage/src/cache/lru_cache.rs
- dragonfly-client-storage/src/cache/mod.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
This PR introduces cache support for piece storage in Dragonfly client to improve performance. Key changes include:
1. Modified Cache initialization to be async and added task deletion support.
2. Added cache integration in storage operations: 
- Added load_to_cache parameter to control caching behavior.
- Implemented cache upload/download operations for pieces.
`pop` in `dragonfly-client-storage/src/cache/lru_cache.rs`[[1]](https://github.com/dragonflyoss/client/pull/1074/files#diff-7d8f8ec7e65a57ac5bd1ee29f70410b71e2be0be94491e27d25af24e7a086231R269): Pop entry from cache.
`delete_task` in `dragonfly-client-storage/src/cache/mod.rs`[[2]](https://github.com/dragonflyoss/client/pull/1074/files#diff-51f0ccb672e36dc2c15f60176ef4f9c63eae4bbf665b32f3a1ad4a5dc8f19f2aR250): Remove task from …
> feat: add cache support for piece download/upload.

- dragonfly-client-storage/benches/cache.rs
- dragonfly-client-storage/src/cache/lru_cache.rs
- dragonfly-client-storage/src/cache/mod.rs
- dragonfly-client-storage/src/lib.rs
This pull request includes several changes to the `dragonfly-client-storage` module, primarily focusing on refactoring the `cache.rs` and `mod.rs` files to simplify the code and improve performance. The changes include the removal of unnecessary unwraps, the use of `Bytes` instead of `Cursor`, and the elimination of redundant code.
* [`dragonfly-client-storage/benches/cache.rs`](diffhunk://#diff-d5e95539e480417a81ef44c3c271689760e0eb23dd969c8409e30af7df7d27deR17-L21): Replaced `Cursor` with `Bytes` for handling data, and removed unnecessary unwraps in cache operations. [[1]](diffhunk://#diff-d5e95539e480417a81ef44c3c271689760e0eb23dd969c8409e30af7df7d27deR17-L21) [[2]](diffhunk://#diff-d5e95539e480417a81ef44c3c271689760e0eb23dd969c8409e30af7df7d27deL227-R215) …
> refactor(dragonfly-client-storage): lru cache support for piece download/upload

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-storage/benches/cache.rs
- dragonfly-client-storage/src/cache/mod.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/resource/piece.rs
This pull request includes several changes to optimize cache configurations and improve code readability in the `dragonfly-client` project. The most important changes include adjusting the cache capacity values, removing unnecessary additions in cache size calculations, and simplifying code in the `Piece` implementation.
* [`dragonfly-client-config/src/dfdaemon.rs`](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddL204-R207): Reduced the default storage cache capacity from 128MiB to 64MiB.
* [`dragonfly-client-storage/benches/cache.rs`](diffhunk://#diff-d5e95539e480417a81ef44c3c271689760e0eb23dd969c8409e30af7df7d27deL197-R197): Removed unnecessary additions in cache size calculations for `write_piece` and `read_piece` functions. …
> test(dragonfly-client-storage/benches): remove 1u64 when create cache

- dragonfly-client-backend/src/lib.rs
Error under MacOS is different(```not a mach-o file```). Let's modify the assert logic.
> fix: modify ut logic which is incorrect under macOS

- dragonfly-client-storage/src/lib.rs
This pull request includes minor changes to the `dragonfly-client-storage` crate, specifically around logging. The changes replace error-level logging with informational-level logging for a specific scenario and add the `info` macro to the list of imports.
Logging updates:
* [`dragonfly-client-storage/src/lib.rs`](diffhunk://#diff-09bca31ba146d9bc116819606a37c3f4073946a1e2af40382b3c41e440869e6eL30-R30): Added the `info` logging macro to the `tracing` imports.
* [`dragonfly-client-storage/src/lib.rs`](diffhunk://#diff-09bca31ba146d9bc116819606a37c3f4073946a1e2af40382b3c41e440869e6eL204-R204): Changed the log level from `error!` to `info!` for a failed cache deletion task in the `Storage` implementation.
> feat(dragonfly-client-storage): Change error log to info for cache task deletion failure

- Cargo.lock
- Cargo.toml
- dragonfly-client-util/src/id_generator/mod.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/header.rs
- dragonfly-client/src/proxy/mod.rs
This pull request introduces significant refactoring and enhancements to the `dragonfly-client` codebase, focusing on improving task ID generation by introducing parameterized enums, updating method signatures, and adding support for content-based task ID calculation. Additionally, it updates dependencies and introduces new headers for flexibility in task ID calculation.
* Introduced `TaskIDParameter` and `PersistentCacheTaskIDParameter` enums to encapsulate parameters for task ID generation, replacing the previous method signatures that required multiple arguments. (`dragonfly-client-util/src/id_generator/mod.rs`) [[1]](diffhunk://#diff-0facc381d7000044e4fade29b772456b0234ce8f1fa844d8f487bafa375bb6f1R35-R62) [[2]](diffhunk://#diff-0facc381d7000044e4fade29b772456b0234ce8f1fa844d8f487bafa37 …
> feat(dragonfly-client): add support for content-based task ID generation in Dragonfly client

- .github/workflows/pr-labels.yml
This pull request introduces a new GitHub Actions workflow to ensure pull requests are properly labeled with one of the predefined labels. 
* [`.github/workflows/pr-labels.yml`](diffhunk://#diff-cc6cdcc79d6a4cb86fb60d52a99f98fa1241bf2da9b359dd211e4f67d72edd19R1-R20): Added a new workflow named "PR Label" that triggers on pull request events (e.g., opened, labeled, unlabeled, synchronize). It uses the `mheap/github-action-required-labels` action to enforce that exactly one label from the set `bug`, `enhancement`, `documentation`, or `dependencies` is applied to the pull request.
> chore(.github/workflows): add pr labels action

- .github/workflows/stale.yml
This pull request introduces a new GitHub Actions workflow to automatically manage stale issues and pull requests. The workflow identifies and labels inactive issues and PRs, and eventually closes them after a defined period of inactivity.
* [`.github/workflows/stale.yml`](diffhunk://#diff-b5e0854ed0838024d5cc25b4e030922e34648b9ea8c432807e35495fb805b894R1-R29): Added a new workflow named "Close stale issues and PRs" that runs on a schedule and can also be triggered manually. It uses the `actions/stale` action to label issues and PRs as stale after 90 days of inactivity, and closes them after an additional 60 days. The workflow includes customizable messages and exemptions for specific labels and milestones.
> chore(.github/workflows): add stale action

- Cargo.lock
- ci/Dockerfile.dfinit
- dragonfly-client-storage/src/content.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-util/Cargo.toml
- dragonfly-client-util/src/fs/mod.rs
- dragonfly-client-util/src/lib.rs
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/dynconfig/mod.rs
- dragonfly-client/src/resource/task.rs
This pull request introduces enhancements to task creation and storage management in the Dragonfly client, with a focus on preallocating file space using the `fallocate` function for improved performance and reliability. It also includes updates to function signatures, test cases, and a new utility module for file system operations.
* Updated `create_task` and `create_persistent_cache_task` methods in `Content` to include a `length` parameter for preallocating file space using the newly introduced `fallocate` function. (`dragonfly-client-storage/src/content.rs`, [[1]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL154-R155) [[2]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL401-R410)
* Modified `download_task_started` …
> feat: support fallocate for creating task

- dragonfly-client/src/resource/piece.rs
This pull request includes a change to the `MAX_PIECE_LENGTH` constant in the `dragonfly-client` codebase, increasing its value to allow larger pieces of data to be processed.
Resource configuration update:
* [`dragonfly-client/src/resource/piece.rs`](diffhunk://#diff-475bfaadbebd4a013fc563ecdf5dc59fc9f5258738fc46ff30b0ac3cea0ad515L49-R49): Increased `MAX_PIECE_LENGTH` from `16 * 1024 * 1024` to `64 * 1024 * 1024`, likely to support larger data pieces in the resource handling logic.
> feat(dragonfly-client): change MAX_PIECE_LENGTH to 64MiB

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
…
This pull request updates the version of the Dragonfly client and makes several important changes to the configuration defaults and documentation in the `dfdaemon` module. The key changes include increasing default timeout values and enhancing the documentation for the scheduler's timeout behavior.
* Updated the Dragonfly client version from `0.2.26` to `0.2.27` in `Cargo.toml` and all workspace dependencies. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31)
* Increased the default timeout for downloading a piece from 15 seconds to 60 seconds in the `default_download_piece_timeout` function.
* Increased the default scheduler scheduling timeout …
> feat(dragonfly-client-config): change the default value oft the schedule_timeout

- dragonfly-client/src/resource/persistent_cache_task.rs
- dragonfly-client/src/resource/piece_collector.rs
- dragonfly-client/src/resource/task.rs
Modify scheduling logic in persistent_cache_task.rs and task.rs to use strict inequality (>) for max_schedule_count comparison, ensuring tasks abort only after exceeding the configured limit. Correct piece collection logic in piece_collector.rs to abort tasks when collected_pieces is empty, fixing the condition for both PieceCollector and PersistentCachePieceCollector to align with intended behavior.
> fix: scheduling and piece collection logic for task abortion

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/resource/piece.rs
This pull request introduces several changes to enhance timeout handling in the Dragonfly client, particularly for download and storage operations. Key updates include extending timeouts, adding a new timeout configuration for writing pieces to storage, and improving error handling for timeout scenarios. Below is a breakdown of the most important changes grouped by theme:
* Increased the default timeout for downloading a piece from 60 seconds to 120 seconds in `default_download_piece_timeout` (`dragonfly-client-config/src/dfdaemon.rs`).
* Added a new configuration `default_storage_write_piece_timeout` with a default value of 90 seconds for writing pieces to storage (e.g., disk or cache) (`dragonfly-client-config/src/dfdaemon.rs`). …
>  feat(dragonfly-client-storage): add write_piece_timeout to storage config and enhance piece download timeout handling

- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client/src/resource/piece.rs
This pull request includes changes to optimize download behavior and improve logging in the `dragonfly-client` project. The most important changes involve reducing the default concurrent piece download count and adding logging for completed pieces.
* [`dragonfly-client-config/src/dfdaemon.rs`](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddL152-R152): Reduced the default number of concurrent pieces to download from `16` to `8` to optimize resource usage and potentially improve stability.
* [`dragonfly-client/src/resource/piece.rs`](diffhunk://#diff-475bfaadbebd4a013fc563ecdf5dc59fc9f5258738fc46ff30b0ac3cea0ad515R425): Added `info` log statements to indicate when a piece or a persistent cache piece is finished and retrieved locally. This change appears in …
> feat(dragonfly-client): add logs for finished piece from local

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/resource/persistent_cache_task.rs
- dragonfly-client/src/resource/task.rs
This pull request replaces the use of `.inspect_err` with `.unwrap_or_else` in multiple locations across the `PersistentCacheTask` and `Task` implementations. This change ensures that errors are handled explicitly without propagating them further, improving error handling and making the code more robust.
* Replaced `.inspect_err` with `.unwrap_or_else` to handle errors when sending `DownloadPieceFinishedRequest` and `DownloadPieceFinishedResponse`, ensuring errors are logged and the `interrupt` flag is set appropriately. [[1]](diffhunk://#diff-f95fb90718c7b67c4be3b2561b7ef633f021db56a99b04eb237aa1dac285ebf8L1148-R1154) [[2]](diffhunk://#diff-f95fb90718c7b67c4be3b2561b7ef633f021db56a99b04eb237aa1dac285ebf8L1174-R1180) [[3]](diffhunk://#diff-f95fb90718c7b67c4be3b2561b7ef633f021db56a99b04eb23 …
> feat(dragonfly-client): replace inspect_err with unwrap_or_else for error handling in piece download requests

- dragonfly-client-util/src/id_generator/mod.rs
This pull request updates the `IDGenerator` in `dragonfly-client-util` to include the `TaskType` in its hashing logic and modifies the associated test cases to reflect the new behavior. These changes ensure that task IDs are now uniquely influenced by their task type, improving the specificity of the generated IDs.
* Added `TaskType::Standard` and `TaskType::PersistentCache` to the hashing logic in the `IDGenerator` implementation, ensuring task IDs are differentiated by their task type. [[1]](diffhunk://#diff-0facc381d7000044e4fade29b772456b0234ce8f1fa844d8f487bafa375bb6f1R155-R156) [[2]](diffhunk://#diff-0facc381d7000044e4fade29b772456b0234ce8f1fa844d8f487bafa375bb6f1R211-R212)
* Updated expected hash values in `mod tests` to align with the new hashing logic that incorporates …
> feat: add task type to ID generation for Standard and PersistentCache tasks

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/grpc/mod.rs
This pull request includes updates to the `Cargo.toml` file to bump the version of multiple dependencies and the package itself, as well as a change to the `REQUEST_TIMEOUT` constant in the `grpc` module to extend the timeout duration and provide additional documentation.
* Updated the package version in `Cargo.toml` from `0.2.28` to `0.2.29`.
* Updated the versions of several workspace dependencies (`dragonfly-client`, `dragonfly-client-core`, `dragonfly-client-config`, etc.) in `Cargo.toml` from `0.2.28` to `0.2.29`.
* Increased the `REQUEST_TIMEOUT` constant in `dragonfly-client/src/grpc/mod.rs` from 5 seconds to 15 seconds and added detailed documentation explaining its purpose and relation to scheduler configuration.
> feat: increase GRPC REQUEST_TIMEOUT to 15 seconds and add comment

- .github/workflows/lint.yml
- Cargo.lock
- Cargo.toml
- dragonfly-client/src/resource/task.rs
This pull request includes updates to the `Cargo.toml` file and introduces new functionality in the `dragonfly-client` project. The changes primarily involve version updates for dependencies and a new feature for handling hard links during task processing.
* Updated the workspace version from `0.2.29` to `0.2.30` in `Cargo.toml`. This includes all related dependencies such as `dragonfly-client`, `dragonfly-client-core`, `dragonfly-client-config`, and others. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31)
* Added logic in `dragonfly-client/src/resource/task.rs` to handle hard link creation for task files. The behavior depends on the …
> feat: add hardlink when task is downloaded

- Cargo.lock
- Cargo.toml
- dragonfly-client-init/src/bin/main.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/tracing/mod.rs
This pull request introduces significant updates to the OpenTelemetry tracing setup in the `dragonfly-client` project. The changes modernize the tracing infrastructure by replacing the Jaeger exporter with an OTLP exporter and adding support for enhanced resource attributes. Additionally, the `init_tracing` function now accepts a `Host` parameter to provide contextual metadata for tracing.
* Updated `tracing-opentelemetry` to version `0.30.0` and replaced Jaeger dependencies with OTLP-related dependencies (`opentelemetry`, `opentelemetry-otlp`, and `opentelemetry_sdk`). These changes enable the use of the OTLP exporter for tracing.
* Enhanced the `init_tracing` function to support the OTLP exporter by configuring `opentelemetry_sdk::trace::SdkTracerProvider` with resource attributes like …
> feat(tracing): migrate to OpenTelemetry OTLP and enrich trace metadata

- ci/Dockerfile
- ci/Dockerfile.debug
- ci/Dockerfile.dfinit
- ci/dfdaemon.service
- docs/performance-optimization.md
- dragonfly-client-backend/examples/plugin/README.md
- dragonfly-client-init/src/bin/main.rs
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/tracing/mod.rs
This pull request introduces a change in the logging mechanism across multiple components of the project. The key update replaces the `--verbose` flag with a new `--log-to-stdout` flag for enabling detailed logs. This change affects Dockerfiles, service files, documentation, and the logging initialization function.
* `ci/Dockerfile`, `ci/Dockerfile.debug`, and `ci/Dockerfile.dfinit`: Updated the `cargo build` command to use the `--log-to-stdout` flag instead of `--verbose` for logging. [[1]](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL37-R37) [[2]](diffhunk://#diff-13f9c6664d42189b9dcb3443624a438ddd6ed0cab1893f225226779346027944L37-R37) [[3]](diffhunk://#diff-4bc49af73ee4c312bbe45791f2bb95c950ecc719ca34b5bf59af0649db904dc5L37-R37)
* …
> feat: add --log-to-stdout for command

- ci/Dockerfile
- ci/Dockerfile.debug
- ci/Dockerfile.dfinit
- ci/dfdaemon.service
- docs/performance-optimization.md
- dragonfly-client-backend/examples/plugin/README.md
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/tracing/mod.rs
This pull request introduces changes to improve logging configuration and build processes across multiple components of the Dragonfly project. The key updates include replacing the `--log-to-stdout` option with `--console` for logging, updating related documentation, and enhancing build commands for better verbosity.
* [`dragonfly-client/src/tracing/mod.rs`](diffhunk://#diff-0bb89dc9b5d2ef0bccfaf41d4a4255fc6cad63be28c3890f60110dad2e62cc79L47-R47): Replaced the `log_to_stdout` parameter with `console` in the `init_tracing` function, and updated the corresponding logic to determine the logging level. [[1]](diffhunk://#diff-0bb89dc9b5d2ef0bccfaf41d4a4255fc6cad63be28c3890f60110dad2e62cc79L47-R47) [[2]](diffhunk://#diff-0bb89dc9b5d2ef0bccfaf41d4a4255fc6cad63be28c3890f60110dad2e62cc79L56-R56)
* …
> feat: rename --log-to-stdout to --console

- dragonfly-client-init/src/bin/main.rs
> feat: rename option log_to_stdout console for dfinit

- Cargo.lock
- Cargo.toml
- dragonfly-client/Cargo.toml
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/resource/piece_collector.rs
In the early stage, the pieces are downloaded from a non-dispersed set of parents, resulting in most pieces being downloaded from a single parent. This uneven bandwidth allocation impacts the overall download speed.
This strategy is particularly effective when downloading multiple pieces simultaneously, as it naturally spreads the workload across the available parent pool.
The collection process works in two phases:
1. **Synchronization Phase**: Waits for a configured duration (DEFAULT_WAIT_FOR_PIECE_FROM_DIFFERENT_PARENTS) to collect the same piece information from different parents. This allows the collector to gather multiple sources for each piece.
2. **Selection Phase**: After the wait period, randomly selects one parent from the available candidates for each piece and forwards it to …
> feat: collects pieces from multiple parents with load balancing strategy

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/grpc/dfdaemon_upload.rs
For the first sync, if the task has started downloading, wait for the first piece to begin downloading. This prevents the child from receiving an empty piece, which would cause disconnection from the parent and rescheduling. Waiting ensures the child avoids unnecessary rescheduling and maximizes the chance to download pieces from the parent.
> feat: if the task has started downloading, wait for the first piece to begin downloading

- ci/Dockerfile
This pull request updates the dependencies in the `ci/Dockerfile` to streamline the development environment and enhance utility tools. The most significant changes involve replacing and adding packages to better suit the project's requirements.
* [`ci/Dockerfile`](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL58-R60): Replaced `infiniband-diags` and `ibverbs-utils` with `iperf3` and `fio` to focus on network performance and I/O benchmarking tools.
* [`ci/Dockerfile`](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL58-R60): Added new packages such as `iotop`, `vim`, `graphviz`, `lsof`, `socat`, and `strace` to enhance debugging, visualization, and monitoring capabilities.
> chore(ci/Dockerfile): add tools for base image

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-init/src/bin/main.rs
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/tracing/mod.rs
This pull request introduces updates to the versioning in `Cargo.toml` and adds enhancements to tracing functionality in the `dragonfly-client` and `dragonfly-client-config` crates. The most significant changes include the addition of a configurable tracing path, updates to the `Tracing` struct and its default implementation, and adjustments to tracing initialization logic to support dynamic endpoint path construction.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15): Updated all dependencies from version `0.2.39` to `0.2.40`. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31)
* …
> feat: support HTTPS protocol for otel

- dragonfly-client/src/tracing/mod.rs
This pull request includes a single change to the `init_tracing` function in the `dragonfly-client/src/tracing/mod.rs` file. The change updates the URL construction logic to dynamically use the specified protocol (`http` or `https`) instead of defaulting to `http`.
- [`dragonfly-client/src/tracing/mod.rs`](diffhunk://#diff-0bb89dc9b5d2ef0bccfaf41d4a4255fc6cad63be28c3890f60110dad2e62cc79L138-R138): Modified the `init_tracing` function to use the `protocol` variable for constructing the OTLP endpoint URL, ensuring compatibility with both `http` and `https`.
> fix: OTLP endpoint URL parsing to correctly include protocol in tracing module

- Cargo.lock
- Cargo.toml
This pull request updates the versioning in the `Cargo.toml` file to reflect a major release, moving from version `0.2.42` to `1.0.0`. It also updates the dependencies to align with the new version.
Versioning updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15): Changed the workspace package version from `0.2.42` to `1.0.0`, indicating a major release.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31): Updated all `dragonfly-client` dependencies to use version `1.0.0`, ensuring consistency across the workspace.
> chore: update cargo version to 1.0.0

- dragonfly-client/src/resource/task.rs
This pull request includes a minor change to the error message in the `Task` implementation in `dragonfly-client/src/resource/task.rs`. The updated message removes the term "persistent cache," simplifying the phrasing for clarity.
> feat: Update error message in task.rs to remove 'persistent cache' reference

- ci/Dockerfile
- ci/Dockerfile.debug
- ci/Dockerfile.dfinit
This pull request introduces architecture-specific build configurations for the Dragonfly client in multiple Dockerfiles. The changes ensure compatibility with `linux/arm64` by setting the `JEMALLOC_SYS_WITH_LG_PAGE` environment variable during the build process.
Architecture-specific build configurations:
* [`ci/Dockerfile`](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL37-R41): Added `ARG TARGETARCH` and conditional logic to set `JEMALLOC_SYS_WITH_LG_PAGE=16` for `linux/arm64` builds before running `cargo build` for `dfget`, `dfdaemon`, and `dfcache`.
* [`ci/Dockerfile.debug`](diffhunk://#diff-13f9c6664d42189b9dcb3443624a438ddd6ed0cab1893f225226779346027944L37-R41): Added `ARG TARGETARCH` and conditional logic to set `JEMALLOC_SYS_WITH_LG_PAGE=16` for …
> chore(Dockerfile): support jemalloc for 64K page size

- dragonfly-client-backend/src/lib.rs
- dragonfly-client/src/bin/dfget/main.rs
Create a blacklist of backends that do not support directory downloads. Currently only http and https can't download directory. This helps the backend plugin to download the directory
> feat: Create a blacklist of backends that do not support directory downloads

- Cargo.lock
- dragonfly-client/Cargo.toml
- dragonfly-client/src/tracing/mod.rs
This pull request introduces a new dependency for panic tracing and integrates it into the tracing initialization process in the `dragonfly-client` project. The most important changes include adding the `tracing-panic` crate and setting up a panic hook using this crate.
* [`dragonfly-client/Cargo.toml`](diffhunk://#diff-651fbc571d827abadd8e14ed21f83bc11941b8733f2d9704b93ae13b4dbfbb31R68): Added the `tracing-panic` crate (version `0.1.2`) to enhance panic handling during runtime tracing.
* [`dragonfly-client/src/tracing/mod.rs`](diffhunk://#diff-0bb89dc9b5d2ef0bccfaf41d4a4255fc6cad63be28c3890f60110dad2e62cc79R206): Integrated the `tracing-panic` crate by setting a custom panic hook using `std::panic::set_hook`. This ensures that panic events are captured and logged via the tracing system.
> feat: add panic log for tracing

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/lib.rs
This pull request includes updates to the versioning of dependencies and workspace packages in `Cargo.toml`, along with a change to the default plugin directory path in `dragonfly-client-config`. These changes ensure compatibility with the new version `1.0.3` and adjust the default directory structure for Linux systems.
* Updated the workspace package version from `1.0.2` to `1.0.3` in `Cargo.toml`. This reflects a new release of the package.
* Updated the versions of all `dragonfly-client` dependencies in `Cargo.toml` from `1.0.2` to `1.0.3` to maintain consistency with the new release.
* Changed the default plugin directory for Linux systems in the `default_plugin_dir` function from `/var/lib/dragonfly/plugins/` to `/usr/local/lib/dragonfly/plugins/` in …
> feat: update default plugin directory to /usr/local/lib/dragonfly/plugins/ on Linux

- dragonfly-client-backend/src/lib.rs
This pull request includes a small fix to the `dragonfly-client-backend/src/lib.rs` file. The change corrects the variable name in a warning message to use `backend_plugin_dir` instead of the incorrect `plugin_dir`.
> fix: logging message in BackendFactory to reference correct backend_plugin_dir variable

- dragonfly-client-config/src/dfdaemon.rs
This pull request includes a small change to the `dragonfly-client-config/src/dfdaemon.rs` file. The change adds a `#[serde(rename = "schedulerClusterID")]` attribute to the `scheduler_cluster_id` field to specify a custom serialization name.
> fix: rename scheduler_cluster_id in the host config

- Cargo.lock
- Cargo.toml
- dragonfly-client/src/grpc/dfdaemon_download.rs
This pull request makes a minor change to the permissions of a Unix domain socket in the `DfdaemonDownloadServer` implementation. The permissions have been updated from `0o660` to `0o777` to allow broader access.
* [`dragonfly-client/src/grpc/dfdaemon_download.rs`](diffhunk://#diff-303fb9e5802b43f6e4657a81ed3ea511a911a64d8bf32abb0d1bea5cc127498dL151-R151): Changed the permissions for the Unix domain socket from `0o660` (read/write for owner and group) to `0o777` (read/write/execute for everyone).
> feat(dragonfly-client): change permissions of download grpc uds

- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
This pull request simplifies the timeout handling logic in the `DfdaemonDownload` implementation by removing the custom timeout parsing logic and defaulting to the configured `piece_timeout` value.
* Removed the logic for parsing and validating a custom `timeout` from the request, including error handling and metrics collection for invalid timeouts. The implementation now directly uses the `piece_timeout` value from the configuration (`self.config.download.piece_timeout`). (`dragonfly-client/src/grpc/dfdaemon_download.rs`, [dragonfly-client/src/grpc/dfdaemon_download.rsL770-L780](diffhunk://#diff-303fb9e5802b43f6e4657a81ed3ea511a911a64d8bf32abb0d1bea5cc127498dL770-L780))
* Updated the `timeout` field in the `backend.head` call to always use the configured `piece_timeout`, ensuring …
> feat: use piece_timeout for list task entries

- Cargo.lock
- dragonfly-client-backend/src/lib.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/bin/dfget/main.rs
Include files in the downloaded directory, use relative path. e.g. --include-files='*.txt' --include-files='*.txt'
- Include files in the downloaded directory, use relative path.
- Support regular expression matching, e.g. 'dir/*', '*.txt'.
- Support illegal path checking
> feat: add include-files argrument in the downloaded directory

- Cargo.lock
- Cargo.toml
- dragonfly-client-backend/src/lib.rs
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfcache/import.rs
- dragonfly-client/src/bin/dfcache/main.rs
- dragonfly-client/src/bin/dfcache/stat.rs
- dragonfly-client/src/bin/dfget/main.rs
- Updated function signature to use references (`&Url`, `&[String]`) for efficiency.
- Improved error handling with detailed `ValidationError` messages instead of generic `UnexpectedResponse`.
- Renamed `rel_path_to_entry` to `entries_by_relative_path` for better clarity.
- Replaced `Vec` with `HashSet` for filtered entries to avoid duplicates.
- Simplified parent directory path construction using `join("")`.
- Enhanced doc comments to clearly describe functionality and behavior.
- Streamlined pattern compilation and iteration using `iter()`.
> refactor(dfget): Improve logic and error handling in `filter_entries`

- dragonfly-client/src/proxy/mod.rs
This pull request updates the logging instrumentation in the `dragonfly-client` proxy module to use the term "url" instead of "uri" for consistency and clarity. The changes affect both the `handler` and `upgraded_handler` functions.
* [`dragonfly-client/src/proxy/mod.rs`](diffhunk://#diff-6421011d65f9faa2a693ea46e321cc00e07b77ef8792a1b795d1db98d9e5ec4cL234-R234): Updated the `#[instrument]` macro in both `handler` and `upgraded_handler` functions to replace the `uri` field with `url`. [[1]](diffhunk://#diff-6421011d65f9faa2a693ea46e321cc00e07b77ef8792a1b795d1db98d9e5ec4cL234-R234) [[2]](diffhunk://#diff-6421011d65f9faa2a693ea46e321cc00e07b77ef8792a1b795d1db98d9e5ec4cL559-R559)
* [`dragonfly-client/src/proxy/mod.rs`](diffhunk://#diff-6421011d65f9faa2a693ea46e321cc00e07b77ef8792a1b795d1db98d …
> feat: rename tracing field from `uri` to `url` in proxy handler functions

- Cargo.lock
- Cargo.toml
- dragonfly-client-backend/src/http.rs
This pull request includes updates to the versioning in `Cargo.toml` and an enhancement to the HTTP backend implementation to improve response handling. The most important changes are outlined below:
* Updated the workspace package version from `1.0.7` to `1.0.8` to reflect the new release. (`Cargo.toml`, [Cargo.tomlL15-R15](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15))
* Updated dependencies (`dragonfly-client` and related crates) to version `1.0.8` for consistency with the new release. (`Cargo.toml`, [Cargo.tomlL25-R31](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31))
* Added a `Range` header (`bytes=0-`) to HTTP requests in the `dragonfly-client-backend` to ensure the `Content-Length` is included in …
> feat: add Range header to ensure Content-Length is returned in response headers

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/src/lib.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/task.rs
This pull request removes the `load_to_cache` field and adds trait method definitions to `dfdaemon_download.rs` and `dfdaemon_upload.rs`.
- Removed cache-related processing from Task handling.
- Added trait method definitions such as `download_cache_task` to `dfdaemon_download.rs` and `dfdaemon_upload.rs` to comply with the API format of version 2.1.55.
- Aim to allow Task to focus on disk interactions while delegating memory cache operations to CacheTask.
> feat:removes the load_to_cache field

- .cargo/config.toml
- Cargo.lock
- Cargo.toml
- ci/Dockerfile
- ci/Dockerfile.debug
- ci/Dockerfile.dfinit
- dragonfly-client-backend/src/http.rs
- dragonfly-client/Cargo.toml
- dragonfly-client/src/tracing/mod.rs
This pull request introduces improvements to tracing and debugging capabilities, updates dependency versions, and addresses a double-decompression issue in HTTP downloads. The most significant changes are grouped below:
* Added the `console-subscriber` dependency to `dragonfly-client` and enabled the console tracing layer when log level is set to TRACE, allowing for better visibility into spawned tasks during debugging. (`dragonfly-client/Cargo.toml`, `dragonfly-client/src/tracing/mod.rs`) [[1]](diffhunk://#diff-651fbc571d827abadd8e14ed21f83bc11941b8733f2d9704b93ae13b4dbfbb31R88) [[2]](diffhunk://#diff-0bb89dc9b5d2ef0bccfaf41d4a4255fc6cad63be28c3890f60110dad2e62cc79R105-R114)
* Updated `tokio` dependency to include the `tracing` feature, and added configuration to enable `tokio_unstable` …
> feat: enable console subscriber layer for tracing spawn tasks on `127.0.0.1:6669` when log level is TRACE

- dragonfly-client/src/proxy/header.rs
- dragonfly-client/src/proxy/mod.rs
This pull request adds support for including the server's IP address in the response headers for requests handled by the Dragonfly proxy. The main focus is to provide clients with information about which server processed their request by introducing a new response header and updating the relevant code paths to populate it.
**Header support improvements:**
* Introduced a new constant `DRAGONFLY_SERVER_IP_HEADER` in `header.rs` to represent the response header key for the server's IP address.
* Updated the `make_response_headers` function in `mod.rs` to accept a `server_ip` parameter and insert the server IP into the response headers using the new header key. [[1]](diffhunk://#diff-6421011d65f9faa2a693ea46e321cc00e07b77ef8792a1b795d1db98d9e5ec4cR1158) …
> feat: add X-Dragonfly-Server-IP for response proxy ip

- ci/Dockerfile
- ci/Dockerfile.debug
This pull request updates the base Golang image version used in both the `ci/Dockerfile` and `ci/Dockerfile.debug` files. The change upgrades from Go 1.23.0 to Go 1.24.0, ensuring that the Docker images use the latest stable Go release for building and installing profiling and gRPC tools.
* Upgraded the base image from `golang:1.23.0-alpine3.20` to `golang:1.24.0-alpine3.20` in both `ci/Dockerfile` [[1]](diffhunk://#diff-3e80aab0c5827bd91cc241afb47e7d83cf0c2dad29dd29c6be31d7ed46d7adecL59-R59) and `ci/Dockerfile.debug` [[2]](diffhunk://#diff-13f9c6664d42189b9dcb3443624a438ddd6ed0cab1893f225226779346027944L61-R61).
> build(ci): update golang version in Dockerfiles

- Cargo.lock
- Cargo.toml
- dragonfly-client-util/src/fs/mod.rs
This pull request makes minor updates to the workspace versioning and improves filesystem compatibility in the project.
* Bumped the workspace package version in `Cargo.toml` from `1.0.16` to `1.0.17`, and updated all internal dependencies to use the new version for consistency. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L15-R15) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L25-R31)
Filesystem compatibility:
* Updated the `fallocate` function in `dragonfly-client-util/src/fs/mod.rs` to gracefully handle unsupported fallocate operations by logging a warning and skipping preallocation, improving compatibility with filesystems that do not support this feature.
> fix(fs): handle unsupported fallocate errors gracefully

- Cargo.lock
- Cargo.toml
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-storage/src/lib.rs
- dragonfly-client-util/src/request/selector.rs
- dragonfly-client/src/bin/dfcache/export.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/grpc/dfdaemon_download.rs
- dragonfly-client/src/grpc/dfdaemon_upload.rs
- dragonfly-client/src/proxy/mod.rs
This pull request introduces several improvements and fixes across the storage, upload/download server handlers, configuration, and dependency management in the Dragonfly client. The most notable changes include enhanced overwrite handling during file operations, improved resource cleanup on task failures, updates to API usage, and a dependency bump for the `dragonfly-api` crate.
**Overwrite handling improvements:**
* Added logic in both `DfdaemonDownloadServerHandler` and `DfdaemonUploadServerHandler` to check for the `overwrite` flag when the output file already exists. If `overwrite` is true, the server attempts to copy the task output to the specified path, handling errors gracefully and avoiding duplicate error messages. This ensures better user experience and correctness when …
> feat(export): add overwrite option for output files

- Cargo.lock
- dragonfly-client-core/Cargo.toml
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client-storage/Cargo.toml
- dragonfly-client-storage/src/client/mod.rs
- dragonfly-client-storage/src/client/quic.rs
- dragonfly-client-storage/src/server/mod.rs
- dragonfly-client-storage/src/server/quic.rs
- dragonfly-client-util/Cargo.toml
- dragonfly-client-util/src/tls/mod.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
- dragonfly-client/src/resource/piece.rs
- dragonfly-client/src/resource/piece_downloader.rs
This implementation adds QUIC-based client and server components to the dragonfly-client-storage directory to enable efficient piece downloading functionality. The solution provides a reliable, high-performance QUIC communication layer for distributing file pieces across the Dragonfly P2P network.
https://github.com/dragonflyoss/design/pull/8
> feat: Add QUIC Client and Server Implementation for Piece Download in dragonfly-client-storage

- Cargo.toml
- dragonfly-client-core/Cargo.toml
- dragonfly-client-core/src/error/mod.rs
- dragonfly-client-storage/Cargo.toml
- dragonfly-client-storage/src/client/quic.rs
- dragonfly-client-storage/src/server/quic.rs
- dragonfly-client/src/bin/dfget/main.rs
- dragonfly-client/src/resource/piece.rs
This pull request refactors and improves QUIC (using the `quinn` crate) support across the client and storage components, with a particular focus on error handling, configuration, and code clarity. It introduces more granular error variants for QUIC operations, simplifies downloader instantiation, and streamlines connection handling and logging for QUIC servers.
* Added specific error variants for QUIC operations (connect, connection, write, read, etc.) to the `DFError` enum in `dragonfly-client-core/src/error/mod.rs`, enabling more precise error reporting and propagation. Removed old conversion implementations that mapped all QUIC errors to `Unknown`. [[1]](diffhunk://#diff-30b34d1fd4f012f66569fffc95749e5627c7a8bb3720dbcea2fa6659a7a5f85bR173-R204) …
> refactor(quic): integrate QUIC and downloader

- Cargo.lock
- Cargo.toml
- dragonfly-client-storage/Cargo.toml
- dragonfly-client-storage/src/client/mod.rs
- dragonfly-client-storage/src/client/quic.rs
- dragonfly-client-storage/src/client/tcp.rs
- dragonfly-client-storage/src/server/mod.rs
- dragonfly-client-storage/src/server/quic.rs
- dragonfly-client-storage/src/server/tcp.rs
This pull request updates the network configuration and buffer management for both QUIC and TCP clients and servers in the `dragonfly-client-storage` package. The changes standardize buffer sizes and keepalive settings, switch from the `nix` crate to `socket2` for socket operations, and ensure consistent configuration of TCP and QUIC transport parameters. Additionally, all workspace dependencies are bumped to version 1.0.26.
**Network Configuration Improvements:**
* Introduced constants for default send/receive buffer sizes and keepalive intervals in both `client/mod.rs` and `server/mod.rs`, used throughout the client and server implementations for consistent configuration.
* QUIC client and server transport settings now use these constants for keepalive interval, idle timeout, …
> feat(dependencies): update tcp and quic config

- dragonfly-client-storage/Cargo.toml
- dragonfly-client-storage/src/client/tcp.rs
- dragonfly-client-storage/src/server/tcp.rs
This pull request updates how the TCP Fast Open option is set for both the TCP client and server. Instead of passing a boolean value, it now passes an integer value (`3u32`) to the `setsockopt` function, which may be required for compatibility with certain system APIs or to enable specific Fast Open features.
**Networking configuration changes:**
* Updated the `setsockopt` call in both `TCPClient` and `TCPServer` implementations to pass `3u32` instead of `true` for the `TcpFastOpenConnect` option, likely to align with system expectations for enabling TCP Fast Open. (`dragonfly-client-storage/src/client/tcp.rs`, [[1]](diffhunk://#diff-310d4eac37200650a61284af74174f541446de46c9086dca1e90998dcab4916dL188-R188); `dragonfly-client-storage/src/server/tcp.rs`, …
> fix(tcp): remove fast open setting

- Cargo.lock
- dragonfly-client-config/src/dfdaemon.rs
This pull request simplifies the `HostType` enum in the `dragonfly-client-config` crate by removing the `Strong` and `Weak` variants, along with all related logic and tests. The changes help streamline the codebase and reduce unnecessary complexity.
Enum simplification:
* Removed the `Strong` and `Weak` variants from the `HostType` enum in `dfdaemon.rs`, leaving only `Normal` and `Super` as valid host types.
Display and serialization logic updates:
* Updated the `fmt::Display` implementation for `HostType` to remove handling for the deleted variants.
* Removed test cases and serialization/deserialization logic related to the `Strong` and `Weak` variants, ensuring tests only cover the remaining valid variants. [[1]](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815 …
> refactor(dfdaemon): remove unused HostType variants

- Cargo.lock
- ci/Dockerfile
- ci/Dockerfile.debug
- ci/Dockerfile.dfinit
- dragonfly-client-config/src/dfdaemon.rs
- dragonfly-client-storage/src/client/tcp.rs
- dragonfly-client-storage/src/content_linux.rs
- dragonfly-client-storage/src/content_macos.rs
- dragonfly-client-storage/src/server/tcp.rs
- dragonfly-client-util/Cargo.toml
- dragonfly-client-util/src/net/mod.rs
- dragonfly-client/src/bin/dfdaemon/main.rs
This pull request introduces support for TCP Fast Open (TFO) in the storage server and client, making network connections more efficient by reducing latency during TCP handshakes. It adds configuration options, implements platform-specific logic for enabling TFO on Linux, and cleans up platform checks in file comparison logic. The most important changes are grouped below:
**TCP Fast Open Support**
* Added a new `tcp_fastopen` boolean field to the `StorageServer` struct in `dfdaemon.rs`, with documentation and a default value of `false`. This allows enabling/disabling TCP Fast Open via configuration. [[1]](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddR968-R972) [[2]](diffhunk://#diff-1d4c7839a6a08bcaef14196c90b20366303b24b2826e1bc9123574a815e7c1ddR984)
* …
> feat(tcp): support TCP Fast Open for client and server 
